"""Stage 3C browser smoke: operations dialogs, telemetry settings, capture dialog and the standalone pages."""
import json, os, sys, time
from playwright.sync_api import sync_playwright
BASE = os.environ.get('CLAB_BASE', 'http://127.0.0.1:8090')
SHOTS = os.environ['CLAB_SHOTS']
os.makedirs(SHOTS, exist_ok=True)
errors, checks = [], []
def check(name, ok, info=''):
    checks.append((name, bool(ok), info))
    if not ok: print('  FAIL', name, info)
import atexit
atexit.register(lambda: [print('  ERROR', e) for e in errors])
with sync_playwright() as pw:
    b = pw.chromium.launch()
    ctx = b.new_context(viewport={'width': 1366, 'height': 768})
    p = ctx.new_page()
    p.on('console', lambda m: errors.append(('console', p.url, m.text)) if m.type == 'error' else None)
    p.on('pageerror', lambda e: errors.append(('page', p.url, str(e))))
    def shot(name, full=False): p.screenshot(path=f'{SHOTS}/1366x768-{name}.png', full_page=full)
    def js(code): return p.evaluate(code)
    state = json.loads(p.request.get(BASE + '/api/state').text())
    labs = {l['name']: l for l in state['labs']}
    bgp, ospf = labs['BGP_TheoryToPractice'], labs['ospf-basics']
    # ---- Lab actions ▾ and All lab operations
    p.goto(f'{BASE}/#lab={bgp["id"]}&view=tools'); p.wait_for_selector('#lab-content:not([hidden])')
    p.wait_for_function('() => state.discovery?.connected && current()?.deployment?.status === "Running"', timeout=30000); p.wait_for_timeout(600)
    shot('40-tools')
    tools = js('() => ({grafana: document.getElementById("grafana-open").hidden ? "" : document.getElementById("grafana-open").textContent.trim(), caption: document.getElementById("grafana-caption").textContent, capture: document.getElementById("capture-open").textContent, cap_caption: document.getElementById("capture-caption").hidden})')
    check('tools: Open lab map / dashboard link label and captions', tools['grafana'] in ('Open lab map ↗', 'Open network dashboard ↗') or tools['grafana'] == '' , tools)
    p.click('#lab-actions-button')
    p.wait_for_selector('#lab-actions-menu:not([hidden])')
    menu = js('() => [...document.querySelectorAll("#lab-actions-menu button")].map(b => ({t: b.querySelector("span")?.textContent || b.textContent, d: b.disabled, r: b.querySelector(".menu-reason")?.textContent || ""}))')
    check('lab actions menu: every disabled item carries a visible reason', all(m['r'] for m in menu if m['d']), menu)
    shot('41-lab-actions-menu')
    p.click('#menu-destroy')
    p.wait_for_selector('#operation-review[open]', timeout=15000)
    review = js('() => ({title: document.querySelector("#operation-review h2").textContent, text: document.getElementById("operation-review").textContent, confirm: document.getElementById("op-confirm").textContent, danger: document.getElementById("op-confirm").classList.contains("danger"), save: !!document.getElementById("op-save-first"), tech: !!document.querySelector("#operation-review details summary")})')
    check('destroy review: student title, unsaved-work line, last-save line, danger confirm, Save progress first', review['title'].startswith('Destroy BGP') and 'Configuration changes you have not saved are lost' in review['text'] and ('Last saved' in review['text'] or 'Never saved' in review['text']) and review['confirm'] == 'Destroy lab' and review['danger'] and review['save'] and review['tech'], review)
    check('destroy review: raw command only under Technical details', '/usr/bin/containerlab' not in js('() => [...document.querySelectorAll("#operation-review > p")].map(p => p.textContent).join(" ")') and '/usr/bin/containerlab' in js('() => document.querySelector("#operation-review details pre").textContent'), '')
    shot('42-destroy-review')
    p.click('#op-cancel')
    # Banner-first confirm: a stop on the open lab closes the review, toasts and reports in the banner with View output.
    p.click('#lab-actions-button'); p.wait_for_selector('#lab-actions-menu:not([hidden])')
    p.click('#lab-actions-menu [data-op-action="stop"]'); p.wait_for_selector('#operation-review[open]', timeout=15000)
    stop = js('() => ({title: document.querySelector("#operation-review h2").textContent, confirm: document.getElementById("op-confirm").textContent})')
    check('stop review: title and confirm label', stop['title'] == 'Stop devices?' and stop['confirm'] == 'Stop devices', stop)
    p.click('#op-confirm')
    p.wait_for_function('() => !document.getElementById("operation-review")?.open && !document.getElementById("lab-banner").hidden && /stop/i.test(document.getElementById("lab-banner-text").textContent)', timeout=15000)
    banner = js('() => ({text: document.getElementById("lab-banner-text").textContent, output: !document.getElementById("banner-output").hidden, out: document.getElementById("operation-output")?.open || false, header: document.getElementById("lab-state").textContent})')
    check('confirm: no output window pops up; the banner names the operation with View output', 'stop' in banner['text'].lower() and banner['output'] and not banner['out'], banner)
    shot('42b-operation-banner')
    p.click('#banner-output'); p.wait_for_selector('#operation-output[open]'); p.wait_for_timeout(500)
    shot('42c-operation-running')
    p.click('#operation-output [data-op-close]')
    p.wait_for_function('() => document.getElementById("lab-banner").hidden || !/stop/i.test(document.getElementById("lab-banner-text").textContent)', timeout=30000)
    p.click('#lab-actions-button'); p.wait_for_selector('#lab-actions-menu:not([hidden])')
    p.click('#lab-actions-menu button:has-text("All lab operations")')
    p.wait_for_selector('#lab-operations-dialog[open]'); p.wait_for_timeout(500)
    ops = js('() => ({sections: [...document.querySelectorAll("#lab-operations-dialog .op-sections h3")].map(h => h.textContent), buttons: [...document.querySelectorAll("#lab-operations-dialog [data-op-action]")].map(b => b.textContent.trim()), danger: !!document.querySelector("#lab-operations-dialog .op-danger [data-op-action=destroy]")})')
    check('all lab operations: Deployment / Lab tools / Danger sections with student labels', ops['sections'] == ['Deployment', 'Lab tools', 'Danger'] and 'Start devices' in ops['buttons'] and ops['danger'], ops)
    shot('43-all-lab-operations')
    p.click('#lab-operations-dialog [data-local="telemetry"]')
    p.wait_for_selector('#telemetry-settings-dialog[open]', timeout=15000); p.wait_for_timeout(300)
    tele = js('() => document.getElementById("telemetry-settings-dialog").textContent')
    check('telemetry settings: student sentences, no gNMI jargon in the lead', 'Telemetry' in tele and 'Dashboard:' in tele and 'pygnmi' not in tele, tele[:200])
    shot('44-telemetry-settings')
    p.click('#telemetry-settings-dialog [data-op-close]')
    # ---- Capture dialog from Tools
    p.click('#capture-open'); p.wait_for_selector('#capture-dialog[open]'); p.wait_for_timeout(800)
    cap = js('() => ({ctx: document.getElementById("capture-context").textContent, adv: document.getElementById("capture-advanced-label").textContent, open: document.getElementById("capture-advanced").open, legend: document.getElementById("capture-primary-legend").textContent, status: document.getElementById("capture-status").textContent, start: document.getElementById("capture-prepare").textContent, order: [...document.querySelectorAll("#capture-form > *")].map(e => e.id || e.tagName.toLowerCase())})')
    check('capture dialog: lab context, device picker unfolded first, Start capture', cap['ctx'].startswith('Lab BGP') and cap['adv'] == 'Choose a device' and cap['open'] and cap['start'] == 'Start capture' and cap['order'].index('capture-advanced') < cap['order'].index('fieldset'), cap)
    shot('45-capture-dialog')
    p.click('#capture-close')
    # ---- Manager ▾: Running labs on the VM…, Operation history…
    p.click('#manager-button'); p.wait_for_selector('#manager-menu-list:not([hidden])')
    shot('46-manager-menu')
    p.click('#inspect-all'); p.wait_for_selector('#operation-review[open]', timeout=15000)
    inspect = js('() => ({title: document.querySelector("#operation-review h2").textContent, confirm: document.getElementById("op-confirm").textContent, text: document.getElementById("operation-review").textContent})')
    check('running labs review: read-only wording and Show running labs', inspect['title'] == 'Refresh the list of running labs on the VM' and inspect['confirm'] == 'Show running labs' and 'Nothing is changed' in inspect['text'], inspect)
    shot('47-inspect-all-review')
    p.click('#op-cancel')
    p.click('#manager-button'); p.wait_for_selector('#manager-menu-list:not([hidden])')
    p.click('#operations-history'); p.wait_for_selector('#operation-history[open]', timeout=15000)
    hist = js('() => ({title: document.querySelector("#operation-history h2").textContent, rows: [...document.querySelectorAll("#operation-history [data-job] strong")].map(s => s.textContent)})')
    check('operation history: student action names in rows', hist['title'].startswith('Operation history') and all(' · ' in r for r in hist['rows']), hist)
    shot('48-operation-history')
    if hist['rows']:
        p.click('#operation-history [data-job]'); p.wait_for_selector('#operation-output[open]'); p.wait_for_timeout(800)
        out = js('() => ({h2: document.querySelector("#operation-output h2").textContent, banner: document.getElementById("op-job-banner").textContent})')
        check('operation output: banner with student action name', '✔' in out['banner'] or '✖' in out['banner'], out)
        shot('49-operation-output')
        p.click('#operation-output [data-op-close]')
    p.click('#operation-history [data-op-close]')
    # ---- Advanced tab: deployment details wording, remove lab dialog
    p.goto(f'{BASE}/#lab={ospf["id"]}&view=advanced'); p.wait_for_selector('#lab-content:not([hidden])'); p.wait_for_timeout(600)
    adv = js('() => ({files: document.getElementById("vm-files-status").textContent, msg: document.getElementById("deployment-message").textContent, vm: document.getElementById("vm-summary").textContent, banner: document.getElementById("lab-banner-text").textContent, detail: document.getElementById("lab-banner-detail-text").textContent, start: document.getElementById("banner-start").textContent})')
    check('advanced: VM status sentence and no raw status words', adv['vm'].startswith('Lab VM:') and adv['start'] == 'Start lab', adv)
    shot('50-advanced', full=True)
    p.click('#remove-lab'); p.wait_for_selector('#remove-lab-dialog[open]')
    rem = js('() => ({title: document.getElementById("remove-lab-title").textContent, danger: document.querySelector("#remove-lab-form button[type=submit]").classList.contains("danger")})')
    check('remove lab dialog: named title and danger submit', rem['title'] == 'Remove ospf-basics from this manager?' and rem['danger'], rem)
    shot('51-remove-lab')
    p.click('#remove-lab-dialog [data-dismiss]')
    # ---- Standalone pages
    p.goto(f'{BASE}/static/workspace.html#mode=ssh&lab={bgp["id"]}'); p.wait_for_selector('#ssh-launch-all', timeout=15000); p.wait_for_timeout(300)
    ws = js('() => ({title: document.getElementById("workspace-title").textContent, doc: document.title, msg: document.getElementById("workspace-message").textContent, rows: document.querySelectorAll(".op-session-row").length, links: document.querySelectorAll(".op-session-row a").length, pills: document.querySelectorAll(".op-session-row .pill").length})')
    check('CLI launcher: Open CLIs title, devices ready sentence, pills and Open CLI links', ws['title'].startswith('Open CLIs · ') and 'devices ready' in ws['msg'] and ws['rows'] == len(bgp['nodes']) and ws['pills'] == ws['rows'] and ws['links'] > 0, ws)
    shot('52-cli-launcher', full=True)
    p.goto(f'{BASE}/static/workspace.html#mode=folder'); p.reload(); p.wait_for_function('() => document.getElementById("workspace-title").textContent !== "" && !document.getElementById("workspace-open").hidden', timeout=15000)
    check('deploy page: student title', js('() => document.getElementById("workspace-title").textContent') == 'Deploy a new lab', '')
    shot('53-deploy-page')
    p.click('#workspace-open'); p.wait_for_selector('#op-browser[open]', timeout=15000); p.wait_for_timeout(500)
    browser = js('() => ({title: document.querySelector("#op-browser h2").textContent, buttons: [...document.querySelectorAll("#op-browser .actions button")].map(b => b.textContent), tree: [...document.querySelectorAll("#op-file-tree summary")].map(s => s.textContent)})')
    check('topology browser: student title, toolbar labels, folder tree', browser['title'] == 'Deploy a new lab' and 'All lab folders' in browser['buttons'] and '/etc/containerlab' in browser['tree'], browser)
    p.click('#op-file-tree summary:has-text("/etc/containerlab")'); p.wait_for_selector('#op-file-tree summary:has-text("examples")', timeout=15000)
    p.click('#op-file-tree summary:has-text("examples")'); p.wait_for_selector('#op-file-tree .op-tree-file', timeout=15000)
    shot('53b-topology-browser')
    p.click('#op-file-tree .op-tree-file'); p.wait_for_selector('#op-editor[open]', timeout=15000); p.wait_for_timeout(300)
    editor = js('() => ({title: document.querySelector("#op-editor h2").textContent, buttons: [...document.querySelectorAll("#op-editor .actions button")].map(b => b.textContent)})')
    check('topology file dialog: Preview topology / Add to My labs / Deploy lab', editor['buttons'] == ['Preview topology', 'Add to My labs without starting', 'Deploy lab'], editor)
    p.click('#op-validate'); p.wait_for_selector('#op-map-preview[open]', timeout=15000); p.wait_for_timeout(300)
    shot('53c-topology-preview')
    p.click('#op-map-preview [data-op-close]'); p.click('#op-editor [data-op-close]'); p.click('#op-browser [data-op-close]')
    p.goto(f'{BASE}/static/debug.html'); p.wait_for_function('() => /^Updated /.test(document.getElementById("debug-status").textContent)', timeout=15000)
    dbg = js('() => ({h1: document.querySelector("h1").textContent, cards: [...document.querySelectorAll("#debug-summary h2")].map(h => h.textContent), first: [...document.querySelectorAll("#debug-summary dt")].slice(0,4).map(d => d.textContent)})')
    check('diagnostics: page name and card titles', dbg['h1'] == 'Diagnostics' and dbg['cards'] == ['This manager', 'VM connection', 'Saved in this manager'] and dbg['first'] == ['Version', 'Python', 'Running for', 'Activity log'], dbg)
    p.click('#debug-probe'); p.wait_for_function('() => document.querySelectorAll("#debug-checks p").length >= 2', timeout=120000)
    probe = js('() => [...document.querySelectorAll("#debug-checks p")].map(p => p.textContent)')
    check('diagnostics: probe rows use student names and an uppercase status', all(r.startswith(('Folder listing — ', 'VM commands — ')) for r in probe), probe)
    shot('54-diagnostics', full=True)
    p.goto(f'{BASE}/static/grafana.html#path=%2Fd%2Fclab-map-abc&title=BGP_TheoryToPractice'); p.wait_for_timeout(1500)
    gf = js('() => ({title: document.getElementById("grafana-title").textContent, headline: document.getElementById("grafana-headline").textContent, status: document.getElementById("grafana-status").textContent, retry: document.getElementById("grafana-retry").hidden})')
    check('network dashboard page: headline sentence with the raw reason as details', gf['title'] == 'Network dashboard · BGP_TheoryToPractice' and gf['headline'] and gf['status'], gf)
    shot('55-network-dashboard')
    p.goto(f'{BASE}/static/terminal.html#lab={bgp["id"]}&node={next(n for n in bgp["nodes"] if n.get("ssh_ready"))["name"]}&label=BGP_TheoryToPractice'); p.wait_for_timeout(2500)
    term = js('() => ({title: document.getElementById("title").textContent, back: document.getElementById("back").textContent, status: document.getElementById("status").textContent, raw: document.getElementById("status").title, notice: document.getElementById("notice-text").textContent, connect: document.getElementById("connect").textContent})')
    check('terminal: device-first title, back link, student status with the raw reason in the title', term['title'].endswith(' · BGP_TheoryToPractice') and term['back'] == '← BGP_TheoryToPractice' and term['connect'] == 'Reconnect' and 'credentials saved for' in term['notice'], term)
    shot('56-terminal')
    p.goto(f'{BASE}/static/capture-setup.html'); p.wait_for_timeout(300); shot('57-capture-setup')
    p.goto(f'{BASE}/vm-connection-guide'); p.wait_for_timeout(300)
    check('vm guide: Diagnostics link', 'Open Diagnostics' in js('() => document.body.textContent'), '')
    b.close()
import atexit
passed = sum(1 for c in checks if c[1])
# A non-2xx answer the page handles (a missing optional file, a probe) is logged by Chromium as a console error; it is reported apart from real errors.
HANDLED = 'Failed to load resource: the server responded with a status of '
handled = [e for e in errors if e[0] == 'console' and e[2].startswith(HANDLED)]
real = [e for e in errors if e not in handled]
print(f'{passed}/{len(checks)} checks passed, console errors {sum(1 for e in real if e[0]=="console")}, page errors {sum(1 for e in real if e[0]=="page")}, handled HTTP error responses {len(handled)}')
sys.exit(0 if passed == len(checks) and not real else 1)
