import sys, re
sys.path.insert(0, 'docs/git-redesign/tools/live')
from l2lib import *
LAB = sys.argv[1]; DEV = sys.argv[2]; NODE = sys.argv[3]; TAG = sys.argv[4] if len(sys.argv) > 4 else 'l2-a2'   # lab name, l1lib device key (b-ceos1), map node (ceos1)
s = Live(); p = s.page
s.open_lab(LAB)
s.wait_quiet(LAB)
s.say('A2 on lab %s; chip before: %s' % (LAB, s.chip()))
bad = set_description(DEV, TAG); s.say('device change (%s): errors %s; reads: %s' % (DEV, bad, description_of(DEV)))
move_on_map(s, NODE)
s.say('moved %s on the map by the page; map document revision via API follows' % NODE)
s.reset_counts(); del s.sent[:]
s.click('#git-save-progress')
s.wait_chip('Saving…', timeout=8000)
s.check('A2 Save: nothing typed', s.typed == 0 and s.clicks == 1)
s.say('panel while saving: %r' % s.text('#save-panel-title'))
s.wait_chip(r'^1 save to upload$', timeout=60000)
expect(p.locator('#save-upload')).to_be_enabled(timeout=20000)
s.check('A2 the panel opened by itself', s.visible('#save-panel'))
title, sentence = s.text('#save-panel-title'), s.text('#save-changes')
s.say('panel title %r; sentence %r; to %r' % (title, sentence, s.text('#save-to')))
s.match('A2 the sentence names the device and the map', sentence, r'map')
s.check('A2 the sentence names the device', 'ceos' in sentence or DEV.split('-')[1] in sentence, sentence)
s.click('#save-see')
expect(p.locator('#save-drawer-content .diff-file').first).to_be_visible(timeout=15000)
p.evaluate("document.querySelectorAll('#save-drawer-content details.diff-file').forEach(d=>d.open=true)")
ents = entries(s)
s.say('What changed entries: %s' % ents)
s.check('A2 See changes lists the device file and the map', any(DEV.split('-')[1] in e for e in ents) and any(e.startswith('Map') for e in ents), ents)
lines = changed_lines(s)
for l in lines: s.say('   changed lines of %r: %s' % (l['name'], [x[:100] for x in l['lines']]))
s.click('#save-drawer-actions [data-save-action="upload"]')
s.wait_toast(r'^Uploaded to github\.com\.$', timeout=60000)
s.wait_chip('^Saved ')
s.say('chip after upload: %r' % s.chip())
s.check('A2 the chip reads Saved just now', s.chip() == 'Saved just now', s.chip())
s.say('clicks Save -> See changes -> Upload (drawer): %d, typed %d; without See changes it is Save + Upload = 2' % (s.clicks, s.typed))
print('requests the page sent:'); [print('   ', c[:200]) for c in s.calls(r'/git/|restore|map')]
job = [j for j in s.jobs(LAB) if j['status'] == 'synced'][-1]
s.say('job: %s' % trim(job, ('status', 'note', 'note_auto', 'commit', 'pushed', 'changed_files', 'summary')))
commit = job['commit']
github('after A2'); checkout('VM checkout after A2')
folder = s.prefix(LAB)
tree = [x.split('/')[-1] for x in gh_tree(folder + '/latest/')]
s.say('lab folder %s/latest on GitHub holds: %s' % (folder, sorted(tree)))
s.check('A2 GitHub: topology file, map, one configuration per device', any(x.endswith('.clab.yml') for x in tree) and any(x.endswith('annotations.json') for x in tree) and all(any(x.startswith(d) for x in tree) for d in ('ceos1', 'ceos2')), tree)
print('commit patch lines:'); l1lib.gh_commit_patch(commit, r'ceos1\.cfg|annotations', 16)
s.no_errors('A2')
print(report(s, 'A2')); s.finish()
