import sys, re
sys.path.insert(0, 'docs/git-redesign/tools/live')
from l2lib import *
LAB, DEV, MARK = sys.argv[1], sys.argv[2], sys.argv[3]
s = Live(); p = s.page
s.open_lab(LAB); s.wait_quiet(LAB)
s.say('A4 on %s; chip %s' % (LAB, s.chip()))
set_description(DEV, 'l2-a4')
s.click('#git-save-progress'); s.wait_chip(r'^1 save to upload$', timeout=60000); expect(p.locator('#save-upload')).to_be_enabled(timeout=20000)
sh('bash', '-c', "echo '127.0.0.1 github.com www.github.com api.github.com %s' | sudo tee -a /etc/hosts >/dev/null" % MARK)
s.say('github.com blocked: %s' % sh('getent', 'hosts', 'github.com')[1])
s.reset_counts()
s.click('#save-upload')
s.wait_chip(r'^Upload failed$', timeout=60000)
expect(p.locator('#save-retry')).to_be_visible(timeout=15000)
s.say('chip %r; panel title %r; sentence %r' % (s.chip(), s.text('#save-panel-title'), s.text('#save-changes')))
s.say('panel text: %r' % s.panel().replace('\n', ' | ')[:500])
s.say('buttons: %s; chip dot class: %s' % (p.locator('#save-panel-body button').all_inner_texts(), p.locator('#save-chip-dot').get_attribute('class')))
st = s.lab(LAB); s.say('git_status in /api/state: %s' % st.get('git_status'))
s.shot('A4-upload-failed')
expect(p.locator('#save-retry')).to_be_enabled(timeout=15000)
s.click('#save-retry')   # still blocked
p.wait_for_timeout(8000)
s.say('Try again while still blocked: chip %r; panel %r' % (s.chip(), s.text('#save-panel-title') if s.visible('#save-panel') else None))
s.click('#save-details', count=False)
expect(p.locator('#git-job-dialog')).to_be_visible(timeout=10000)
s.say('Details dialog (first 300 chars): %r' % s.text('#git-job-dialog')[:300].replace('\n', ' | '))
p.locator('#git-job-dialog .close, #git-job-dialog [aria-label="Close"]').first.click()
sh('bash', '-c', "sudo sed -i '/%s/d' /etc/hosts" % MARK)
s.say('network back: %s' % sh('getent', 'hosts', 'github.com')[1])
s.close_panels(); s.open_chip()
if not s.visible('#save-retry'):
    s.say('no Try again visible; panel %r' % s.panel()[:200])
expect(p.locator('#save-retry')).to_be_enabled(timeout=15000)
s.click('#save-retry')
s.wait_toast(r'^Uploaded to github\.com\.$', timeout=60000); s.wait_chip('^Saved ')
s.say('after Try again with the network back: chip %r; clicks since the failure %d' % (s.chip(), s.clicks))
github('after A4 retry')
s.no_errors('A4 (console and request errors are the failed upload\'s own 4xx/5xx if any)')
print(report(s, 'A4')); s.finish()
