"""Live gates K (packet capture + browser Wireshark) and L (telemetry / Grafana)."""
import json, os, re, sys, time, subprocess, urllib.request
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from live_lib import *; import junos_ssh
PTX = node_address('cjunosevolved'); PEER = os.environ.get('PEER_IP', '10.0.0.2')
def get(url, timeout=30):
    try: return urllib.request.urlopen(url, timeout=timeout).read().decode('utf-8', 'replace')
    except Exception as exc: return 'ERR ' + repr(exc)
pw, b, ctx, r = session('stage4a'); p = r.page
def section(name, fn):
    try: fn()
    except Exception as exc:
        r.check(f'{name}: section completed without an exception', False, repr(exc)[:300]); r.shot(f'{name}-exception')
        for sel in ('#capture-close', '[data-op-close]'):
            try:
                loc = p.locator(f'dialog[open] {sel}')
                if loc.count(): loc.first.click(timeout=1000)
            except Exception: pass
        try: p.keyboard.press('Escape')
        except Exception: pass
r.open_lab(); p.wait_for_selector('#topology-map .topology-wire', timeout=15000)
titles = r.js('() => [...document.querySelectorAll("#topology-map .topology-wire title")].map(t => t.textContent)'); r.note('link titles after redeploy + sync', titles)
r.check('N sync: after the redeploy the map links carry the corrected et-0/0/0 / et-0/0/1 names', any('et-0/0/0' in x for x in titles), titles)
wire = p.locator('#topology-map .topology-wire').first; wire.focus(); p.keyboard.press('Enter'); p.wait_for_selector('#capture-dialog[open]', timeout=15000); p.wait_for_timeout(1200)
lk = r.js('() => ({ctx: document.getElementById("capture-context").textContent, legend: document.getElementById("capture-primary-legend").textContent, checked: [...document.querySelectorAll("#capture-interfaces input:checked")].map(i => i.parentElement.textContent.replace(/\\s+/g," ").trim()), labels: [...document.querySelectorAll("#capture-interfaces label")].map(l => l.textContent.replace(/\\s+/g," ").trim()).slice(0,6)})'); r.note('link click capture dialog', lk)
r.check('C/K topology: activating a map link (keyboard) opens Capture traffic on the link endpoint with the wired interface ticked', lk['ctx'].startswith('Link endpoint') and len(lk['checked']) >= 1, lk); r.shot('K-link-click'); p.click('#capture-close')
r.tab('tools'); p.wait_for_timeout(800)
cards = r.js('() => ({grafana: document.getElementById("grafana-open").hidden ? "" : document.getElementById("grafana-open").textContent.trim(), caption: document.getElementById("grafana-caption").textContent, tele: document.getElementById("telemetry-line").textContent, capture: document.getElementById("capture-open").textContent, capDisabled: document.getElementById("capture-open").disabled, cap_caption: document.getElementById("capture-caption").hidden ? "" : document.getElementById("capture-caption").textContent})'); r.note('tools cards', cards)
r.check('K tools: Capture traffic… enabled with the capture stack installed', cards['capture'] == 'Capture traffic…' and not cards['capDisabled'], cards); r.shot('K-tools')
def gate_k():
    p.click('#capture-open'); p.wait_for_selector('#capture-dialog[open]'); p.wait_for_timeout(1500)
    tools_dlg = r.js('() => ({ctx: document.getElementById("capture-context").textContent, adv: document.getElementById("capture-advanced-label").textContent, open: document.getElementById("capture-advanced").open, target: document.getElementById("capture-target")?.tagName, options: [...document.querySelectorAll("#capture-target option")].map(o => o.textContent).slice(0,6), status: document.getElementById("capture-status").textContent})'); r.note('capture dialog from Tools', tools_dlg)
    r.check('K dialog (Tools): the device picker unfolds first when no device is chosen', tools_dlg['open'] and tools_dlg['adv'] == 'Choose a device', tools_dlg); r.shot('K-capture-dialog-tools'); p.click('#capture-close')
    r.tab('devices'); p.locator('#device-list .device-row', has_text='PTX1').locator('[data-details]').first.click(); p.wait_for_selector('#details-dialog[open]'); p.locator('#details-actions button', has_text='Capture traffic').click()
    p.wait_for_selector('#capture-dialog[open]'); p.wait_for_function('() => document.querySelectorAll("#capture-interfaces input[type=checkbox], #capture-more input[type=checkbox]").length > 0 || /no |not /i.test(document.getElementById("capture-status").textContent)', timeout=60000); p.wait_for_timeout(800)
    cap = r.js('() => ({ctx: document.getElementById("capture-context").textContent, target: document.getElementById("capture-target")?.value || document.getElementById("capture-target")?.textContent, ifaces: [...document.querySelectorAll("#capture-interfaces label")].map(l => l.textContent.replace(/\\s+/g," ").trim()), status: document.getElementById("capture-status").textContent, start: document.getElementById("capture-prepare").textContent, refresh: document.getElementById("capture-refresh")?.textContent, sessions: document.getElementById("capture-sessions").textContent.replace(/\\s+/g," ").slice(0,200)})'); r.note('capture dialog', cap)
    r.check('K dialog: device context, target and the wired interfaces listed first', cap['ctx'].startswith('Device:') and len(cap['ifaces']) >= 1, cap)
    more = r.js('() => ({label: document.getElementById("capture-more-label")?.textContent, items: [...document.querySelectorAll("#capture-more label")].map(l => l.textContent.replace(/\\s+/g," ").trim()).slice(0,8)})'); r.note('other interfaces on this device', more)
    if p.locator('#capture-more').count() and not r.js('() => document.getElementById("capture-more").open'): p.click('#capture-more > summary')
    for b in p.locator('#capture-interfaces input[type=checkbox]:checked').all(): b.uncheck()
    real = p.locator('#capture-dialog label', has_text=re.compile(r'^eth4\b')).locator('input[type=checkbox]')
    if real.count(): real.first.check(); r.note('capturing on', 'eth4 (the real et-0/0/0 port of this image)')
    else:
        boxes = p.locator('#capture-interfaces input[type=checkbox]'); boxes.first.check(); r.note('capturing on', 'first wired interface')
    r.shot('K-capture-dialog', full=True); p.click('#capture-prepare')
    p.wait_for_function('() => !document.getElementById("capture-launch").hidden || /failed|error|unavailable|not /i.test(document.getElementById("capture-status").textContent)', timeout=180000); p.wait_for_timeout(500)
    st = r.js('() => ({status: document.getElementById("capture-status").textContent, launch: document.getElementById("capture-launch").hidden ? "" : document.getElementById("capture-launch").textContent, sessions: document.getElementById("capture-sessions").textContent.replace(/\\s+/g," ").slice(0,300)})'); r.note('after Start capture', st)
    r.check('K start: a session is created and Open Wireshark ↗ appears', 'Open Wireshark' in st['launch'], st); r.shot('K-capture-started', full=True)
    with ctx.expect_page(timeout=30000) as pop: p.click('#capture-launch')
    w = pop.value; r.attach(w); w.wait_for_load_state(); w.wait_for_function('() => /Connected|Wireshark|ready/i.test(document.getElementById("viewer-status")?.textContent || "") || !!document.querySelector("#capture-screen canvas, #capture-screen iframe")', timeout=180000); w.wait_for_timeout(6000)
    # generate harmless traffic on the captured link
    ping = '\n'.join(junos_ssh.cli(PTX, [f'ping {PEER} count 5 rapid'])); r.note('ping from PTX1', ping[-300:])
    w.wait_for_timeout(6000)
    vs = w.evaluate('() => ({title: document.title, status: document.getElementById("viewer-status")?.textContent, canvas: !!document.querySelector("#capture-screen canvas, #capture-screen iframe, canvas"), name: document.getElementById("capture-name")?.textContent, dl: !!document.getElementById("capture-download"), end: !!document.getElementById("capture-end")})'); r.note('wireshark viewer', vs)
    r.check('K Wireshark: the browser viewer page connects and draws the remote screen', vs['canvas'] and (vs['status'] or '').lower().find('connected') >= 0 or vs['canvas'], vs); r.shot('K-wireshark', page=w)
    sessions = json.loads(get(BASE + '/api/capture/sessions') or '{}'); r.note('sessions api', json.dumps(sessions)[:600])
    dockers = subprocess.run(['sudo', '-n', 'docker', 'ps', '--format', '{{.Names}} {{.Image}}'], capture_output=True, text=True).stdout; ws = [l for l in dockers.splitlines() if 'wireshark' in l.lower()]; r.note('wireshark containers', ws)
    r.check('K Wireshark: a labelled Wireshark container exists on the VM for the session', len(ws) >= 1, dockers[:400])
    r.check('K packets: ping traffic generated on the captured link answered', '5 packets transmitted' in ping and ('5 packets received' in ping or 'received' in ping), ping[-200:])
    w.close()
    p.click('#capture-sessions-refresh') if p.locator('#capture-sessions-refresh').count() else None; p.wait_for_timeout(1500)
    endb = p.locator('[data-end-capture]').first; r.check('K sessions: the session is listed with End session', endb.count() >= 1, r.js('() => document.getElementById("capture-sessions").textContent.slice(0,200)'))
    endb.click(); p.wait_for_timeout(1000)
    conf = p.locator('dialog[open] #op-confirm, dialog[open] button.danger, dialog[open] button.primary')
    if conf.count() and 'End' in (conf.first.text_content() or ''): conf.first.click()
    p.wait_for_function('() => document.querySelectorAll("[data-end-capture]").length === 0', timeout=60000); p.wait_for_timeout(2000)
    dockers2 = subprocess.run(['sudo', '-n', 'docker', 'ps', '--format', '{{.Names}}'], capture_output=True, text=True).stdout; r.check('K end: the session and its Wireshark container are gone, nothing leaked', 'wireshark' not in dockers2.lower() and not json.loads(get(BASE + '/api/capture/sessions') or '{}').get('sessions'), dockers2[:300])
    r.shot('K-capture-ended'); p.click('#capture-close')
if os.environ.get('SECTIONS', 'KL').count('K'): section('K', gate_k)
def gate_l():
    for _ in range(3):
        if r.js('() => !!document.querySelector("dialog[open]")'): p.keyboard.press('Escape'); p.wait_for_timeout(300)
    r.tab('tools'); p.wait_for_timeout(500)
    p.click('#tools-telemetry-settings'); p.wait_for_selector('#telemetry-settings-dialog[open]', timeout=15000); p.wait_for_timeout(500)
    tele = r.js('() => document.getElementById("telemetry-settings-dialog").textContent.replace(/\\s+/g," ")'); r.note('telemetry settings', tele[:700])
    r.check('L settings: student sentences with a Dashboard: line and per-device streaming state', tele.startswith('Telemetry settings') and 'Dashboard:' in tele and ('PTX1' in tele or 'SW1' in tele), tele[:200]); r.shot('L-telemetry-settings', full=True); p.click('#telemetry-settings-dialog [data-op-close]')
    metrics = get(BASE + '/api/telemetry/metrics'); names = sorted(set(re.findall(r'^([a-z_]+)\\{', metrics, re.M))); r.note('manager metrics families', names[:20])
    r.check('L metrics: the manager exposes interface metrics for the lab', any('interface' in n for n in names) and 'clab-llm-dev2' in metrics, names)
    with ctx.expect_page(timeout=30000) as pop: p.click('#grafana-open')
    g = pop.value; r.attach(g); g.wait_for_load_state(); g.wait_for_timeout(1500)
    head = g.evaluate('() => ({title: document.title, headline: document.getElementById("grafana-headline")?.textContent, status: document.getElementById("grafana-status")?.textContent, url: location.href})'); r.note('grafana launcher page', head)
    r.check('L launcher: transition page explains what is happening', bool(head['headline']) and ('start' in (head['headline'] + head['status']).lower() or 'dashboard' in (head['headline'] + head['status']).lower()), head); r.shot('L-grafana-launcher', page=g)
    t0 = time.time()
    while time.time() - t0 < 180:
        if ':3000' in g.url: break
        g.wait_for_timeout(2000)
    r.note('grafana final url', g.url); r.check('L Grafana: started on demand and the lab dashboard opened (redirect to :3000)', ':3000' in g.url and ('/d/' in g.url or 'dashboards' in g.url), g.url)
    g.wait_for_timeout(15000); r.shot('L-grafana-dashboard', page=g)
    gtxt = g.evaluate('() => document.body.innerText.slice(0, 1500)'); r.note('grafana page text', gtxt[:600])
    r.check('L Grafana: the opened dashboard names the lab / its devices, no plugin error banner', ('clab-llm-dev2' in gtxt or 'PTX1' in gtxt or 'SW1' in gtxt) and 'plugin' not in gtxt.lower().split('error')[0][-40:] and 'Plugin not found' not in gtxt, gtxt[:300])
    health = get('http://127.0.0.1:3000/api/health'); r.note('grafana health', health[:200])
    search = get('http://127.0.0.1:3000/api/search?query='); r.note('grafana dashboards', search[:800])
    r.check('L Grafana: healthy and the generated lab map dashboard is provisioned', '"database": "ok"' in health.replace(' ', '').replace('"database":"ok"', '"database": "ok"') and 'clab-llm-dev2' in search, (health[:100], search[:200]))
    targets = get('http://127.0.0.1:9090/api/v1/targets'); r.note('prometheus targets', targets[:600])
    r.check('L Prometheus: the manager target is up', '"health":"up"' in targets, targets[:300])
    q1 = get('http://127.0.0.1:9090/api/v1/query?query=' + urllib.request.quote('clab_interface_oper_state{lab="clab-llm-dev2"}')); r.note('prom oper_state query', q1[:400])
    q2 = get('http://127.0.0.1:9090/api/v1/query?query=' + urllib.request.quote('{__name__=~"clab_interface_.*rate.*|clab_interface_.*bytes.*",lab="clab-llm-dev2"}')); r.note('prom rate query', q2[:400])
    r.check('L Prometheus: live interface state samples for the lab are present', '"resultType":"vector"' in q1 and 'clab-llm-dev2' in q1, q1[:200])
    gname = next((l for l in subprocess.run(['sudo', '-n', 'docker', 'ps', '--format', '{{.Names}}'], capture_output=True, text=True).stdout.splitlines() if 'grafana' in l), 'grafana'); glog = subprocess.run(['sudo', '-n', 'docker', 'logs', '--tail', '300', gname], capture_output=True, text=True); logs = (glog.stdout + glog.stderr); errs = [l for l in logs.splitlines() if 'level=error' in l]; r.note('grafana error log lines', errs[:8])
    r.check('L Grafana: no plugin or dashboard-query errors in the Grafana log', not any('plugin' in l.lower() or 'dashboard' in l.lower() or 'query' in l.lower() for l in errs), errs[:5])
    g.close()
if os.environ.get('SECTIONS', 'KL').count('L'): section('L', gate_l)
r.report('stage4a'); b.close(); pw.stop()
