"""Live gates E (Save progress, first save), F (checkpoint), G (folder browser + nested folder), H (versions/compare), J (downloads)."""
import json, os, re, sys, time, subprocess
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from live_lib import *
CHECKPOINT = os.environ.get('CHECKPOINT', 'release-1.29-live-validation'); NESTED = os.environ.get('NESTED', 'Week-01/BGP/Final-State')
pw, b, ctx, r = session('stage2'); p = r.page
def section(name, fn):
    try: fn()
    except Exception as exc:
        r.check(f'{name}: section completed without an exception', False, repr(exc)[:300]); r.shot(f'{name}-exception'.replace(' ', '_'))
        for sel in ('#git-first-cancel', '#git-save-cancel', '#git-new-folder-cancel', '#git-folder-cancel', '[data-op-close]'):
            try:
                loc = p.locator(f'dialog[open] {sel}')
                if loc.count(): loc.first.click(timeout=1000)
            except Exception: pass
def git(*args): return subprocess.run(['git', '-C', os.path.expanduser('~/labs/CLAB-MNGR-DEV-LLM')] + list(args), capture_output=True, text=True).stdout.strip()
r.open_lab(); r.tab('progress'); p.wait_for_selector('#git-save-location', timeout=15000); p.wait_for_timeout(800)
def gate_e():
    first = r.js('() => ({button: document.getElementById("git-save-progress").textContent, disabled: document.getElementById("git-save-progress").disabled, destination: document.getElementById("git-destination").textContent, head: document.querySelector("#git-save-location h2")?.textContent, folderOpen: document.getElementById("git-change-folder")?.open, header: document.getElementById("lab-progress").textContent})')
    r.note('progress unbound', first)
    if first['button'] == 'Connect a save location…':
        r.check('E first save: unbound lab offers Connect a save location… and Choose a save location', not first['disabled'] and first['head'] == 'Choose a save location', first); r.shot('E-progress-unbound', full=True)
        p.click('#git-save-progress'); p.wait_for_selector('#git-first-save-dialog[open]', timeout=15000); p.wait_for_timeout(500)
        dlg = r.js('() => ({title: document.querySelector("#git-first-save-dialog h2").textContent, repos: [...document.querySelectorAll("#git-first-repo option")].map(o => o.textContent), folders: [...document.querySelectorAll("#git-first-folder option")].map(o => o.textContent), devices: [...document.querySelectorAll("#git-first-save-dialog input[type=checkbox]")].map(c => c.name || c.id), text: document.getElementById("git-first-save-dialog").textContent.replace(/\\s+/g," ").slice(0,700)})')
        r.note('first-save dialog', dlg)
        r.check('E first save: dialog asks where, lists the registered repository and its folder', dlg['title'].startswith('Where should') and any('CLAB-MNGR-DEV-LLM' in x or 'clab-llm-dev2' in x for x in dlg['repos'] + dlg['folders']), dlg)
        r.shot('E-first-save-dialog', full=True)
        if not p.locator('#git-first-ack').is_checked(): p.check('#git-first-ack')
        p.click('#git-first-confirm'); p.wait_for_timeout(1500)
        err = r.js('() => document.querySelector("#git-first-save-dialog .form-error, #git-first-save-dialog [role=alert]")?.textContent || ""'); r.note('first save with the suggested folder', {'folder': r.js('() => document.getElementById("git-first-folder").value'), 'error': err})
        r.check('G first save: a folder that would contain another lab folder is refused with a plain sentence', 'cannot overlap' in err and 'clab-llm-dev2/work' in err, err); r.shot('G-first-save-overlap-refused')
        p.fill('#git-first-folder', 'clab-llm-dev2/work'); p.click('#git-first-confirm')
    else:
        r.check('E first save: lab already bound (skipping first-save dialog)', True, first); p.click('#git-save-progress')
    p.wait_for_function('() => document.getElementById("git-save-progress").textContent === "Saving…" || /Saving|Saved/.test(document.getElementById("lab-progress").textContent)', timeout=20000)
    r.check('E save: header button reads Saving…', r.js('() => document.getElementById("git-save-progress").textContent') == 'Saving…', r.js('() => document.getElementById("git-save-progress").textContent')); r.shot('E-saving')
    p.wait_for_function('() => document.getElementById("git-save-progress").textContent === "Save progress" && !/Saving/.test(document.getElementById("git-progress-status").textContent)', timeout=420000)
    p.wait_for_timeout(1500)
    after = r.js('() => ({status: document.getElementById("git-progress-status").textContent, header: document.getElementById("lab-progress").textContent, destination: document.getElementById("git-destination").textContent, saves: [...document.querySelectorAll("#git-saves-list .git-saved-job > summary")].map(s => s.textContent.trim()).slice(0,3), problem: document.getElementById("git-problem").hidden, jobOpen: !!document.getElementById("git-job-dialog")?.open, jobTitle: document.querySelector("#git-job-dialog h2")?.textContent, jobText: document.getElementById("git-job-detail")?.textContent.replace(/\\s+/g," ").slice(0,500)})')
    r.note('after save', after)
    r.check('E save: status card reads Saved to Git and the header agrees', after['status'].startswith('Saved to Git') and after['header'].startswith('Saved to Git'), after)
    r.check('E save: destination names the repository folder', 'clab-llm-dev2' in after['destination'], after['destination'])
    r.check('E save: recent save row says Progress saved to Git', any('Progress saved to Git' in s for s in after['saves']), after['saves'])
    r.shot('E-after-save', full=True)
    if after['jobOpen']: p.click('#git-job-dialog [data-op-close]')
    st = git('status', '--short'); log = git('log', '--oneline', '-3'); ahead = git('rev-list', '--count', 'origin/main..main'); git('fetch', '-q', 'origin'); behind = git('rev-list', '--count', 'main..origin/main'); ahead2 = git('rev-list', '--count', 'origin/main..main')
    files = git('ls-tree', '-r', '--name-only', 'HEAD', 'clab-llm-dev2/work'); staged = git('diff', '--cached', '--name-only')
    r.note('VM git after save', {'status': st, 'log': log, 'ahead_of_origin': ahead2, 'behind': behind, 'files': files, 'staged': staged})
    r.check('E git: checkout clean after the save, nothing staged', st == '' and staged == '', st)
    r.check('E git: commit exists under clab-llm-dev2/work/latest with manifest, .set and .jcfg files', 'clab-llm-dev2/work/latest/manifest.json' in files and '.set' in files and '.jcfg' in files, files)
    r.check('E git push: local main is pushed (0 commits ahead of origin/main after fetch)', ahead2 == '0', ahead2)
    remote = subprocess.run(['gh', 'api', 'repos/pruger-dev/CLAB-MNGR-DEV-LLM/commits/main', '--jq', '.sha'], capture_output=True, text=True).stdout.strip()
    r.check('E git push: GitHub main equals the local HEAD', remote == git('rev-parse', 'HEAD'), (remote, git('rev-parse', 'HEAD')))
section('E', gate_e)
def gate_f():
    p.click('#progress-view [data-git-action="checkpoint"]'); p.wait_for_selector('#git-save-options[open]'); p.fill('#git-checkpoint-name', CHECKPOINT); p.wait_for_timeout(300)
    prev = r.js('() => ({value: document.getElementById("git-checkpoint-name").value, preview: document.getElementById("git-checkpoint-preview").textContent})'); r.note('checkpoint preview', prev)
    r.check('F checkpoint: live Saved as preview matches the sanitised name', prev['preview'].startswith('Saved as: ') and prev['preview'].split(': ',1)[1] == prev['value'], prev); r.shot('F-checkpoint-dialog')
    p.click('#git-save-confirm')
    p.wait_for_function('() => document.getElementById("git-save-progress").textContent === "Saving…" || document.getElementById("git-save-progress").textContent === "Save progress"', timeout=20000)
    p.wait_for_function('() => document.getElementById("git-save-progress").textContent === "Save progress" && !/Saving/.test(document.getElementById("git-progress-status").textContent)', timeout=420000); p.wait_for_timeout(1500)
    if r.js('() => !!document.getElementById("git-job-dialog")?.open'): r.note('job dialog after checkpoint', r.js('() => document.getElementById("git-job-dialog").textContent.replace(/\\s+/g," ").slice(0,400)')); p.click('#git-job-dialog [data-op-close]')
    p.wait_for_function('(n) => [...document.querySelectorAll("#git-saved-versions .git-version-row")].some(x => x.textContent.includes(n))', arg=prev['value'], timeout=60000)
    rows = r.js('() => [...document.querySelectorAll("#git-saved-versions .git-version-row")].map(x => x.textContent.replace(/\\s+/g," ").trim().slice(0,160))'); r.note('saved version rows', rows)
    cp = [x for x in rows if prev['value'] in x]; latest = [x for x in rows if x.startswith('Latest') or 'Latest' in x]
    r.check('F checkpoint: appears in Saved versions', bool(cp), rows)
    times = re.findall(r'(\d{1,2}:\d{2}|\d+ (?:seconds?|minutes?) ago|just now)', ' '.join(cp)); r.note('checkpoint row times', times)
    files = git('ls-tree', '-r', '--name-only', 'HEAD', 'clab-llm-dev2/work/checkpoints'); r.note('checkpoint files', files)
    r.check('F checkpoint: repository layout checkpoints/<name>/ with manifest and configs', f'clab-llm-dev2/work/checkpoints/{prev["value"]}/manifest.json' in files, files)
    r.check('F checkpoint: Git history records it and it is pushed', prev['value'] in git('log', '-3', '--stat', '--format=%s') and git('rev-list', '--count', 'origin/main..main') == '0', git('log', '-2', '--oneline'))
    r.shot('F-saved-versions', full=True)
section('F', gate_f)
def gate_h():
    p.locator('#git-saved-versions [data-git-version-action="view"]').first.click(); p.wait_for_selector('#git-version-dialog[open]'); p.wait_for_function('() => document.querySelectorAll("#git-version-dialog li, #git-version-dialog pre, #git-version-dialog table tr").length > 0', timeout=60000); p.wait_for_timeout(500)
    v = r.js('() => ({title: document.querySelector("#git-version-dialog h2").textContent, text: document.getElementById("git-version-dialog").textContent.replace(/\\s+/g," ").slice(0,600), apply: !!document.getElementById("git-version-restore") && !document.getElementById("git-version-restore").hidden, compare: document.getElementById("git-version-compare")?.textContent, dl: document.getElementById("git-version-download")?.textContent})'); r.note('version dialog', v)
    r.check('H view: Saved version dialog lists files with Compare with my latest save and Download (ZIP)', v['title'] == 'Saved version' and v['compare'] == 'Compare with my latest save' and v['dl'] == 'Download (ZIP)' and '.set' in v['text'], v)
    r.check('H view: a Junos restore-grade version offers Apply to running lab…', v['apply'], v['apply'])
    with p.expect_download(timeout=60000) as dl: p.click('#git-version-download')
    d = dl.value; path = os.path.join(OUT, 'stage2-version.zip'); d.save_as(path)
    import zipfile; names = zipfile.ZipFile(path).namelist(); r.note('version zip', {'filename': d.suggested_filename, 'entries': names})
    r.check('H view: ZIP downloads with the configuration files', d.suggested_filename.endswith('.zip') and any(n.endswith('.set') for n in names) and any(n.endswith('manifest.json') for n in names), names)
    r.shot('H-saved-version'); p.click('#git-version-dialog [data-op-close]')
    cmp = p.locator('#git-saved-versions .git-version-row', has_text=CHECKPOINT.replace('.', '-')).locator('[data-git-version-action="compare"]')
    if cmp.count() == 0: cmp = p.locator('#git-saved-versions [data-git-version-action="compare"]')
    cmp.first.click(); p.wait_for_selector('#git-diff-dialog[open]'); p.wait_for_function('() => document.getElementById("git-diff-dialog").textContent.length > 80', timeout=60000); p.wait_for_timeout(500)
    diff = r.js('() => ({title: document.querySelector("#git-diff-dialog h2").textContent, text: document.getElementById("git-diff-dialog").textContent.replace(/\\s+/g," ").slice(0,500), html: document.getElementById("git-diff-dialog").innerHTML.includes("<script"), pre: document.querySelectorAll("#git-diff-dialog pre, #git-diff-dialog .diff-line, #git-diff-dialog ins, #git-diff-dialog del").length})'); r.note('compare', diff)
    r.check('H compare: titled Compared with your latest save, never running configuration', diff['title'] == 'Compared with your latest save' and 'running configuration' not in diff['text'].lower(), diff)
    r.check('H compare: renders a result (identical or a diff) with no HTML injection', (('No differences' in diff['text'] or 'identical' in diff['text'].lower() or 'same' in diff['text'].lower()) or diff['pre'] > 0) and not diff['html'], diff)
    r.shot('H-compare', full=True); p.click('#git-diff-dialog [data-op-close]')
    p.click('#git-saved-versions [data-git-version-action="view"] >> nth=0')
section('H', gate_h)
try: p.click('#git-version-dialog [data-op-close]', timeout=2000)
except Exception: pass
def gate_g():
    p.click('#git-change-folder > summary'); p.wait_for_selector('#git-places-panel .git-places-head', timeout=30000); p.wait_for_timeout(800)
    places = r.js('() => ({use: document.querySelector("[data-git-places-action=use]")?.textContent, useDisabled: document.querySelector("[data-git-places-action=use]")?.disabled, new: document.querySelector("[data-git-places-action=new]")?.textContent, crumbs: [...document.querySelectorAll(".git-crumbs button")].map(b => b.textContent), heading: document.querySelector("#git-change-folder h3")?.textContent, text: document.getElementById("git-places-panel").textContent.replace(/\\s+/g," ").slice(0,900)})'); r.note('places', places)
    r.check('G places: browser shows the repository with Save this lab here and New folder…', places['use'] == 'Save this lab here' and (places['new'] or '').startswith('New folder') and places['heading'] == 'Folders in this repository', places)
    r.check('G places: this lab tagged and the other labs of the repository visible', 'This lab' in places['text'] and ('bgp-core' in places['text'] or 'BGP-LAB' in places['text']), places['text'][:300])
    r.shot('G-places', full=True)
    # navigate into an existing other-lab folder: Save this lab here must be refused/disabled for latest/ and other labs
    for label in ('bgp-core', 'work'):
        btn = p.locator('#git-places-panel button', has_text=re.compile(rf'^{label}\\b')).first
        if btn.count(): btn.click(); p.wait_for_timeout(700)
    guard = r.js('() => ({crumbs: [...document.querySelectorAll(".git-crumbs button")].map(b => b.textContent), useDisabled: document.querySelector("[data-git-places-action=use]")?.disabled, reason: document.querySelector("#git-places-panel .form-help, #git-places-panel .git-places-reason, #git-places-panel [data-git-places-reason]")?.textContent, text: document.getElementById("git-places-panel").textContent.replace(/\\s+/g," ").slice(0,400)})'); r.note('other lab folder guard', guard)
    r.check("G places: another lab's folder cannot be chosen (Save this lab here disabled with a reason)", guard['useDisabled'] and (guard['reason'] or 'another lab' in guard['text'] or 'saves to' in guard['text']), guard)
    r.shot('G-other-lab-folder')
    p.locator('.git-crumbs button').first.click(); p.wait_for_timeout(600)
    p.click('[data-git-places-action=new]'); p.wait_for_selector('#git-new-folder-name', timeout=10000)
    p.fill('#git-new-folder-name', '../etc'); p.wait_for_timeout(300); trav = r.js('() => ({result: document.getElementById("git-new-folder-result").textContent, disabled: document.getElementById("git-new-folder-confirm").disabled})'); r.note('traversal', trav)
    r.check('G new folder: path traversal is rejected in the browser', trav['disabled'] or 'not allowed' in trav['result'].lower() or 'invalid' in trav['result'].lower() or 'Choose' in trav['result'], trav)
    p.fill('#git-new-folder-name', 'clab-llm-dev2/work'); p.wait_for_timeout(300); occ = r.js('() => ({result: document.getElementById("git-new-folder-result").textContent, disabled: document.getElementById("git-new-folder-confirm").disabled})'); r.note('occupied', occ)
    r.check('G new folder: an occupied destination is prevented', occ['disabled'] or 'already' in occ['result'].lower() or 'saves' in occ['result'].lower(), occ)
    p.fill('#git-new-folder-name', NESTED); p.wait_for_timeout(300); prev = r.js('() => ({result: document.getElementById("git-new-folder-result").textContent, disabled: document.getElementById("git-new-folder-confirm").disabled, use: document.getElementById("git-new-folder-use")?.checked})'); r.note('nested preview', prev)
    r.check('G new folder: nested path shows the resulting destination and is allowed', (not prev['disabled']) and NESTED.split('/')[-1] in prev['result'], prev); r.shot('G-new-folder-nested')
    if p.locator('#git-new-folder-use').count() and prev['use']: p.uncheck('#git-new-folder-use')
    p.click('#git-new-folder-confirm'); p.wait_for_function('(n) => !document.querySelector("#git-new-folder-name") || document.getElementById("git-places-panel").textContent.includes(n)', arg=NESTED.split('/')[0], timeout=60000); p.wait_for_timeout(800)
    reg = subprocess.run(['sudo', '-n', 'bash', os.path.expanduser('~/projects/clab-manager/deploy/setup-git.sh'), '--list'], capture_output=True, text=True).stdout; prefixes = re.findall(r'"prefix": "([^"]+)"', reg); r.note('registered prefixes', prefixes)
    r.check('G new folder: nested folder registered on the VM in one step', NESTED in prefixes, prefixes)
    txt = r.js('() => document.getElementById("git-places-panel").textContent.replace(/\\s+/g," ")'); r.check('G places: the new folder appears in the browser (created on first save)', NESTED.split('/')[0] in txt, txt[:300]); r.shot('G-places-after-new-folder', full=True)
    p.click('#git-change-folder > summary')
section('G', gate_g)
def gate_j():
    r.tab('tools'); p.wait_for_timeout(600)
    p.click('#backup'); p.wait_for_timeout(500)
    conf = p.locator('dialog[open] #op-confirm, dialog[open] button.primary, dialog[open] button[type=submit]')
    r.note('backup review', r.js('() => [...document.querySelectorAll("dialog[open]")].map(d => d.textContent.replace(/\\s+/g," ").slice(0,300))'))
    if conf.count(): conf.first.click()
    p.wait_for_function('() => [...document.querySelectorAll("#jobs li, #jobs tr, #jobs .job")].length > 0', timeout=30000)
    p.wait_for_function('() => !busy()', timeout=300000); p.wait_for_timeout(1500)
    jobs = r.js('() => ({items: [...document.querySelectorAll("#jobs li, #jobs .job, #jobs details")].map(x => x.textContent.replace(/\\s+/g," ").trim().slice(0,200)).slice(0,6), links: [...document.querySelectorAll("#backups-view a[href*=download], #backups-view a[download], #jobs a")].map(a => ({t: a.textContent.trim(), href: a.getAttribute("href")})).slice(0,12)})'); r.note('backup history', jobs)
    r.check('J history: the backup history lists jobs with the restore-pre/manual sources and per-device outcomes', any('PTX1' in i or 'SW1' in i for i in jobs['items']), jobs['items'])
    got = []
    btns = p.locator('#jobs [data-download]'); n = btns.count(); r.note('download buttons', [btns.nth(i).text_content() for i in range(min(n, 8))])
    for i in range(min(n, 5)):
        with p.expect_download(timeout=60000) as dl: btns.nth(i).click()
        d = dl.value; path = os.path.join(OUT, 'dl-' + d.suggested_filename); d.save_as(path); size = os.path.getsize(path); head = open(path, 'rb').read(80)
        got.append({'filename': d.suggested_filename, 'bytes': size, 'head': 'zip' if head[:2] == b'PK' else head.decode('utf-8', 'replace')})
    r.note('downloaded', got)
    r.check('J downloads: device files and the whole-backup ZIP download with content', n >= 3 and all(g['bytes'] > 50 for g in got) and any(g['head'] == 'zip' for g in got), got)
    r.check('J downloads: filenames carry the expected extensions and device names', any(g['filename'].endswith('.set') for g in got) and any(g['filename'].endswith('.jcfg') for g in got) and any(g['filename'].endswith('.zip') for g in got) and any('PTX1' in g['filename'] for g in got), [g['filename'] for g in got])
    r.check('J downloads: a display-set file holds Junos set statements and a .jcfg the hierarchical config', any('set ' in g['head'] for g in got if g['filename'].endswith('.set')) and any('{' in g['head'] or 'version' in g['head'] for g in got if g['filename'].endswith('.jcfg')), [g['head'][:40] for g in got])
    r.shot('J-backups', full=True)
section('J', gate_j)
r.report('stage2'); b.close(); pw.stop()
