"""The decided "New outcome" of every row of sections A to D of docs/git-redesign/inventory/REFUSALS.md (R1).

Each cell was decided by reading today's code around the text that match_refusals.py located; `{at}` is replaced
by today's `path:line` of the row's text in its own file (match_refusals.match), written explicitly where the same
text is raised in several places of that file. Paths: `app/` is `clab-backup-ui/app/`. Read by fill_outcomes.py.
"""

CH = {
    'vm': 'chip `vm`: `The lab VM could not be reached.` · Try again · Check the VM connection…',
    'account': 'chip `account`: `The VM account cannot upload to <host>.` · Try again · Details',
    'busy': 'chip `busy`: `Someone is working in this repository on the VM.` · Try again · Details',
    'diverged': 'chip `diverged`: `The online copy has changes this VM does not have.` · Update from the repository (with saves waiting: `…both have changes… combined on the VM.` · Try again · Details, with the owner\'s two commands)',
    'files': 'chip `files`: `<folder> holds files that were not saved by the manager.` · Choose another place · Details',
    'settings': 'chip `settings`: `This lab’s save location has to be set up again.` · Save settings · Details',
    'other': 'chip `other`: `The save did not work.` · Try again · Details',
    'device': 'chip `device` (job `capture_incomplete`): `<device> could not be read, so nothing was saved.` · Try again · Save settings · Details',
    'devices': 'chip `devices`: `No device of this lab is selected for saving.` · Save settings',
}


def kc(code, extra=''):
    return 'Kept: ' + CH[code] + '; full text under Details' + extra + '. {at}'


PLACE409 = ('HTTP 409 of POST …/git/place or …/git/state, recorded as the lab\'s status with code `{code}` (`placement_refused` app/git_progress.py:1015-1022); '
            'the chooser and the first-save panel show that code\'s chip sentence with this text under Details, or this text itself for code `other` '
            '(`drwChooserRefused` save-drawers.js:609-619; `clean_text` app/git_place.py:58-61)')
NR_SNAPSHOT = 'Kept, not reachable through the page: the manager builds the snapshot itself within the same limits (`captured_snapshot` app/git_progress.py:678-787, `MAX_WIRE` :638). {at}'
JOB_DEVICE = 'Kept: save job ends `capture_incomplete` → chip `capture`: this sentence of the manager · Try again · Details (status.js:369; `device` only when a device failed); HTTP 400 on POST …/git/save for a checkpoint or baseline from a stored capture (app/git_progress.py:1977-1978). {at}'
VERSION409 = 'Kept: HTTP 409 in the version view, the What changed drawer or the Load review (`version_data` app/git_progress.py:2281-2285; restore.py:589-590, 643-644). {at}'
TERMINAL = 'Kept: terminal of the deploy script (C7); only an administrator or the repository owner at the VM shell meets it. {at}'

OUT = {
    # ---------------------------------------------------------------- A. app/host_git.py
    'R-001': 'Kept, not reachable through the page: a folder reaches the helper only after `clean_folder` (app/git_places.py:27-39; place routes) or `folder_value` (app/git_progress.py:859-865; old routes), a version path after `resolve_version_path` (:209-223). {at}',
    'R-002': 'Kept, not reachable through the page: same checks first as R-001. {at}',
    'R-003': 'Kept, not reachable through the page: the place and state routes leave a saved-state part first (`leave_state` app/git_places.py:144-158, DESIGN 2.5 step 2) and an existing registration is reused before the check (app/host_git.py:1368-1370); the old routes refuse earlier with the manager copy (R-171). A choice no longer ends here. {at}',
    'R-004': 'Kept: ' + PLACE409 + '. {at}',
    'R-005': 'Kept: ' + PLACE409 + '. {at}',
    'R-006': 'Kept: ' + PLACE409 + ' (the page checks `https://…` first, save-header.js:378); raw on the old …/git/connect. {at}',
    'R-007': 'Kept: as R-006. {at}',
    'R-008': 'Kept: as R-006 (GitHub page links such as /tree/main are rewritten first, app/host_git.py:130-131). {at}',
    'R-009': 'Kept: as R-006 (`repository_name` in `plan_connect`, app/host_git.py:1392). {at}',
    'R-010': kc('settings', '; on POST …/git/place the 409 in the chooser'),
    'R-011': kc('settings', '; on POST …/git/place the 409 in the chooser'),
    'R-012': NR_SNAPSHOT, 'R-013': NR_SNAPSHOT, 'R-014': NR_SNAPSHOT, 'R-015': NR_SNAPSHOT, 'R-016': NR_SNAPSHOT,
    'R-017': NR_SNAPSHOT, 'R-018': NR_SNAPSHOT, 'R-019': NR_SNAPSHOT, 'R-020': NR_SNAPSHOT, 'R-021': NR_SNAPSHOT,
    'R-022': 'Kept (carrier): `exclusive()` raises the caller\'s text after its wait (app/host_git.py:308-324); the texts are R-032 and R-152. Choice: only transiently, as those rows.',
    'R-023': kc('account') .replace('{at}', 'app/host_git.py:356'),
    'R-024': kc('other'),
    'R-025': kc('account').replace('{at}', 'app/host_git.py:359'),
    'R-026': kc('settings', '; on connect the 409 under the address field'),
    'R-027': kc('settings').replace('{at}', 'app/host_git.py:383'),
    'R-028': kc('settings').replace('{at}', 'app/host_git.py:388'),
    'R-029': kc('other'),
    'R-030': kc('account', ' (publish, move); when a folder is registered (`register()` app/host_git.py:1118) the 409 in the chooser'),
    'R-031': 'Kept: only in `register()` (app/host_git.py:1121): ' + PLACE409 + '; 3.6 lists the account that cannot upload. Not in `HELPER_PROBLEMS` (chip `other` if it ever reached a job). {at}',
    'R-032': kc('busy', '; transient: another Git process holds the checkout lock; the manager runs its own helper calls one at a time (app/git_progress.py:889, 937)') + ' Choice: only while that process runs (3.6 last paragraph).',
    'R-033': kc('settings'), 'R-034': kc('settings'), 'R-035': kc('settings'), 'R-036': kc('settings'), 'R-037': kc('settings'),
    'R-038': kc('settings'), 'R-039': kc('settings'), 'R-040': kc('settings'), 'R-041': kc('settings'),
    'R-042': kc('busy', '; when a folder is registered in such a checkout, the 409 in the chooser (`register()` app/host_git.py:1118)'),
    'R-043': kc('busy', '; when a folder is registered, the 409 in the chooser'),
    'R-044': kc('busy', '; when a folder is registered, the 409 in the chooser (scope: the new folder\'s saved-state folders)'),
    'R-045': kc('files'),
    'R-046': kc('files'), 'R-047': kc('files').replace('{at}', 'app/host_git.py:470'), 'R-048': kc('files').replace('{at}', 'app/host_git.py:472'),
    'R-049': kc('files'), 'R-050': kc('files'), 'R-051': kc('files'), 'R-052': kc('files'), 'R-053': kc('files'),
    'R-054': 'Kept, not reachable through the page: operation ids are the manager\'s own 32-hex job ids (`request_id` pattern app/git_progress.py:1604; uuid4 in git_place.py:408). {at}',
    'R-055': kc('other'),
    'R-056': kc('account'),
    'R-057': kc('other'),
    'R-058': kc('other'),
    'R-059': kc('other'), 'R-060': kc('other'), 'R-061': kc('other'),
    'R-062': kc('busy').replace('{at}', 'app/host_git.py:674'),
    'R-063': kc('other', '; the upload goes through the save at HEAD only (app/git_progress.py:2197-2220), so it is met only for a save whose commit failed verification') + ' Choice: no folder involved.',
    'R-064': kc('diverged', ' (DESIGN 3.4 and review S1b 4 want `busy` for commits not made by manager saves: 9.6 M2)'),
    'R-065': kc('busy'),
    'R-066': kc('diverged'),
    'R-067': kc('diverged', ' (DESIGN 3.4 wants `busy`: 9.6 M2)'),
    'R-068': kc('busy'),
    'R-069': kc('account'),
    'R-070': kc('other'),
    'R-071': kc('settings', '; met when root re-registered the folder with other settings, which H7 refuses while a save made through it waits (app/host_git.py:1122-1131)') + ' Choice: no folder involved.',
    'R-072': kc('busy'), 'R-073': kc('busy'), 'R-074': kc('busy'), 'R-075': kc('busy'), 'R-076': kc('busy'), 'R-077': kc('busy'),
    'R-078': kc('other'), 'R-079': kc('other'),
    'R-080': 'Kept, not reachable through the page: `note_value` allows one line of 120 characters (app/git_progress.py:466-473) and the automatic name is one line (`change_name` :523). {at}',
    'R-081': kc('busy'),
    'R-082': 'Kept, not reachable through the page: the publication body is written once before the first publication and every retry reuses it (app/git_progress.py:1313-1323). {at}',
    'R-083': kc('busy').replace('{at}', 'app/host_git.py:775'),
    'R-084': kc('busy', '; transient (HEAD moved between the save\'s `status` and its publication)') + ' Choice: no folder involved.',
    'R-085': 'Kept, not reachable through the page: the target is fixed by the route (app/git_progress.py:1931, 2082, 2127). {at}',
    'R-086': 'Kept, not reachable through the page: the options are booleans of the request models (app/git_progress.py:1988-1990). {at}',
    'R-087': 'Kept, not reachable through the page: a capture manifest carries no `kind` (`captured_snapshot`); only a hand-committed manifest meets it. {at}',
    'R-088': 'Kept, not reachable through the page: a design export always targets its own checkpoint (app/git_progress.py:2127). {at}',
    'R-089': kc('other', '; the baseline dialog sends `replace_baseline` with the digest it showed') + ' Choice: no folder involved.',
    'R-090': 'Kept, not reachable through the page: the manager checks the name (`SLUG` app/git_progress.py:1934, 2107) or derives a free one (`free_checkpoint` :1957). {at}',
    'R-091': kc('other', ' for a typed checkpoint name that exists; a checkpoint from a save gets a free name from the names the manager and the tree know (app/git_progress.py:1917-1927, 1957)'),
    'R-092': kc('files') + ' Choice: no; a design export writes a new checkpoint folder (R-091 first) and `leave_state` never places a lab where a design manifest is `latest`; only a hand-committed design manifest in a lab\'s `latest` or `baseline` meets it (3.6 files row).',
    'R-093': kc('files').replace('{at}', 'app/host_git.py:843'),
    'R-094': kc('files').replace('{at}', 'app/host_git.py:848'),
    'R-095': kc('files') + ' Choice: yes, listed in 3.6 (files row) and 2.3 "Not changed"; the chooser avoids a visible foreign `latest` (step 4, app/git_places.py:173-176, 241-245) but not files inside `baseline` or a checkpoint folder, nor beyond the tree cap.',
    'R-096': kc('files') + ' Choice: as R-095 (listed in 3.6).',
    'R-097': 'Kept, not reachable through the page: `allow_removed` is always true for saves and lab states (app/git_progress.py:1990, 2082); a design export writes a new checkpoint folder. {at}',
    'R-098': kc('busy'),
    'R-099': 'Kept, not reachable through the page: version requests pass the `Version` model and `resolve_version_path` first (app/git_progress.py:1636-1640, 209-223). {at}',
    'R-100': VERSION409, 'R-101': VERSION409, 'R-102': VERSION409, 'R-103': VERSION409, 'R-104': VERSION409, 'R-105': VERSION409,
    'R-106': 'Kept, not reachable through the page: compare runs through the save\'s own binding (app/git_progress.py:2312), whose revision is its journal\'s; a re-registered folder stops earlier at R-138. {at}',
    'R-107': 'Kept: HTTP 409 in the What changed drawer (over 8 MiB). {at}',
    'R-108': 'Kept: HTTP 409 on POST …/git/update and ' + CH['busy'] + ' (app/git_progress.py:2247-2250); transient. {at}',
    'R-109': 'Kept: HTTP 409 on POST …/git/update and ' + CH['diverged'] + '; while saves wait the manager answers WAITING_FIRST before the helper (app/git_progress.py:2236). {at}',
    'R-110': 'Kept: HTTP 409 on POST …/git/update and chip `busy`. {at}',
    'R-111': kc('settings', '; on connect the 409 under the address field (`prepare_state` app/host_git.py:1207)').replace('{at}', 'app/host_git.py:1034'),
    'R-112': kc('settings', '; on connect the 409 under the address field').replace('{at}', 'app/host_git.py:1039'),
    'R-113': 'Kept: HTTP 409 when the chooser or the Load panel reads the tree (GET …/git/places → `checkout_view` → `browse`, app/git_progress.py:1533). {at}',
    'R-114': 'Kept: ' + PLACE409 + ' (`ensure_identity` during connect, app/host_git.py:1214). {at}',
    'R-115': 'Kept: ' + PLACE409 + ' (`check_permission` during connect). {at}',
    'R-116': 'Kept: ' + PLACE409 + '. {at}',
    'R-117': 'Kept: ' + PLACE409 + '. {at}',
    'R-118': 'Kept: ' + PLACE409 + '. {at}',
    'R-119': 'Kept: ' + PLACE409 + ' (`register()` for every new folder and every connect). {at}',
    'R-120': 'Kept: ' + PLACE409 + '. {at}',
    'R-121': 'Kept for the first folder of a checkout (a new clone): ' + PLACE409 + '; a further folder may sit on waiting manager saves (H2, `check_synchronized` app/host_git.py:558-571), where REMOTE_AHEAD and NOT_MANAGER_SAVES (9.8) take its place. app/host_git.py:53, 565',
    'R-122': 'Kept: ' + PLACE409 + '. {at}',
    'R-123': 'Kept: ' + PLACE409 + '. {at}',
    'R-124': 'Kept: ' + PLACE409 + '. {at}',
    'R-125': 'Question (empty): `<name> is empty. The manager adds a README.md file to start it.` · **Start the repository** (H4; app/git_place.py:247-256, `initialize` app/host_git.py:1148); still the raw 409 on the old POST …/git/connect (Save settings › Connect by URL…, FINDING F2). app/host_git.py:56, 1148',
    'R-126': 'Kept, not reachable through the page: the move line is never offered into the lab\'s own folder (`bring` reason `same`, app/git_place.py:180) and the old destination route answers the own folder without a move (app/git_progress.py:1812-1813). A choice no longer ends here. {at}',
    'R-127': 'Kept, not reachable through the page: the manager writes the move\'s note (app/git_place.py:411, app/git_progress.py:1855). {at}',
    'R-128': 'Kept, not reachable through the page: the move request is stored once and reused on retry (app/git_place.py:411-416). {at}',
    'R-129': kc('other', ' (move job)'),
    'R-130': kc('other', ' (move job; transient)') + ' Choice: no folder involved.',
    'R-131': kc('other', ' (move job)'),
    'R-132': kc('other', ' (move job); the chooser offers the move only when the folder the lab leaves holds saved files (`bring` reason `nothing`, app/git_place.py:180); the Progress tab\'s Use dialog offers it for any file count'),
    'R-133': kc('other', ' (move job)'), 'R-134': kc('other', ' (move job)'), 'R-135': kc('other', ' (move job)'),
    'R-136': kc('other', ' (move job, retried in vain)') + ' The chooser never offers the move into a folder that holds saved files (`bring` reason `not-empty`, app/git_place.py:180, 48). FINDING F4: the old POST …/git/destination queues the move whatever the new folder holds (app/git_progress.py:1850-1865) and the Progress tab ticks "Also move" by default.',
    'R-137': kc('other', ' (move job)'),
    'R-138': kc('settings', '; every mode with a binding whose registration root re-registered meanwhile. Choice: no folder involved').replace('{at}', 'app/host_git.py:1292'),
    'R-139': 'Kept, not reachable through the page: the manager sends only the modes it knows. {at}',
    'R-140': 'Kept, not reachable through the page: the manager never sends `owner` (app/git_place.py:250). {at}',
    'R-141': 'Kept: ' + PLACE409 + '. {at}',
    'R-142': 'Kept: ' + PLACE409 + '. {at}',
    'R-143': 'Kept: ' + PLACE409 + ' (an installation whose registered owner is root). {at}',
    'R-144': 'Kept, not reachable through the page: the remote comes from the registry or is `origin` (app/host_git.py:1386, 1392). {at}',
    'R-145': 'Kept: FINDING F1: a folder longer than 97 characters minus the checkout folder\'s name builds a label over 100 characters (app/host_git.py:1375, 1396) and POST …/git/place answers HTTP 409 `Use a short repository label.` in the chooser (app/git_place.py:282-287; reproduced with the real `plan_prefix` and `Placement.register`, 9.5). {at}',
    'R-146': 'Gone (H1): inside, above, beside and the top level are accepted (`colliding` app/host_git.py:157-167, `check_collision` :1353-1356); only a real collision is refused, with the new collision sentence (9.8), which the place route turns into a replace or question 1 with one button (app/git_place.py:279-299). FINDING F2/F4: the old routes still pass that sentence raw.',
    'R-147': 'Kept: race (a registration re-registered between list and plan); the place route reads it fresh (app/git_place.py:329) and shows the 409 text as is (the old routes are not called by the page). app/host_git.py:1366',
    'R-148': 'Kept: ' + PLACE409 + '. {at}',
    'R-149': 'Kept: ' + PLACE409 + ' (generic text of the owner\'s child). {at}',
    'R-150': 'Kept, not reachable through the page: internal guard on the child\'s answer; on the place route it would read `The VM could not use this folder right now. Try again in a moment.` (`clean_text`). {at}',
    'R-151': 'Kept (carrier): the child\'s text as the row of its origin (app/host_git.py:1419); on the place routes through `clean_text` (app/git_place.py:58-61).',
    'R-152': 'Reworded on the place route: `The VM could not use this folder right now. Try again in a moment.` (`clean_text` app/git_place.py:39, 58-61: the text holds "registration"); raw on the old routes; transient (registry lock wait 30 s). {at}',
    'R-153': 'Question (collision, one button): raised only with `retire`, which only the place route\'s replace sends; its ValueError becomes question 1 (app/git_place.py:292-299). app/host_git.py:1444',
    'R-154': 'Kept (race under the registry lock): on the place route a colliding folder saved meanwhile is replaced or asked about (app/git_place.py:284-299); the same folder saved meanwhile reads `The VM could not use this folder right now. Try again in a moment.` and the retry reuses it; raw on the old routes. Choice: only by a race (transient). {at}',
    'R-155': 'Question (collision, one button): raised only on the replace path (`add=False`, app/host_git.py:1474-1482), whose ValueError the place route turns into question 1 (app/git_place.py:297-299). app/host_git.py:1456',
    'R-156': kc('other', '; 409 on the routes (installation problem)'),
    'R-157': kc('other', '; 409 on the routes'),
    'R-158': kc('other', '; 409 on the routes'),
    'R-159': kc('settings', '; 409 on the routes'),
    'R-160': 'Kept, not reachable through the page: the helper starts as root through `sudo -n` from the gateway. {at}',
    'R-161': 'Kept, not reachable through the page: same as R-160. {at}',
    'R-162': 'Kept, not reachable through the page: the manager refuses a request over `MAX_WIRE` itself (app/git_progress.py:638). {at}',
    'R-163': 'Kept, not reachable through the page: the manager always sends an object. {at}',
    'R-164': kc('settings', ' for a save whose registration an older release retired; the place route reads the list fresh (app/git_place.py:329) and the old destination route follows `retired_already` (app/git_progress.py:1485-1498, 1832-1837)'),
    'R-165': kc('other', '; 409 on the routes'),
    'R-166': 'Kept (carrier): `main()` prints every ValueError as `{\'error\': …}` (app/host_git.py:1544-1545).',
    'R-167': kc('other', '; 409 on the routes'),

    # ---------------------------------------------------------------- B. app/git_progress.py
    'R-168': 'Kept: HTTP 400 on …/git/version and …/git/compare for a bare name a page of an older release sends; the page sends tree paths. app/git_progress.py:178',
    'R-169': 'Kept: HTTP 400 for an unsafe version path; the page sends listed folders. app/git_progress.py:205',
    'R-170': 'Kept, not reachable through the page: `Version.path` has `min_length=1` (app/git_progress.py:1639) and a folder source checks its path first (restore.py:620-621). app/git_progress.py:218',
    'R-171': 'Kept on the old routes only (`folder_value` → `base_folder`, app/git_progress.py:863-864, 229-242): HTTP 400. The place and state routes use the folder above instead (2.5 step 2). FINDING F4: in the Progress tab a committed folder named `latest`, `baseline` or `checkpoints` below a folder no lab saves to is choosable (git-places.js `managed` is set only below a registration) and Use sends it to …/git/destination or …/folders. app/git_progress.py:240',
    'R-172': 'Gone (DESIGN 1, 3.4): `sibling_refusal` and `guard_siblings` no longer exist; the review names every save an upload carries (`also_sends`, app/git_progress.py:2317-2361) and the sentence names them (status.js `saveChangeSentence`). Choice: no.',
    'R-173': 'Kept: ' + CH['vm'] + ' (`MANAGER_PROBLEMS` app/git_progress.py:442); HTTP 409 on the routes. app/git_progress.py:636',
    'R-174': 'Kept: ' + CH['other'] + ' (the manager\'s own limit). app/git_progress.py:638',
    'R-175': 'Kept: ' + CH['vm'] + '. app/git_progress.py:654',
    'R-176': 'Kept: ' + CH['vm'] + '. app/git_progress.py:656',
    'R-177': 'Kept: ' + CH['vm'] + '. app/git_progress.py:662',
    'R-178': 'Kept: ' + CH['vm'] + '. app/git_progress.py:668',
    'R-179': 'Kept: ' + CH['vm'] + '. app/git_progress.py:669',
    'R-180': 'Kept (carrier): the helper\'s text cut to 600 characters (app/git_progress.py:670), then scrubbed by `invoke` (:938-940).',
    'R-181': 'Kept: ' + CH['vm'] + '. app/git_progress.py:672',
    'R-182': 'Kept: HTTP 400 on POST …/git/save for a checkpoint or baseline from a capture that is not complete; the page offers kept captures only (`capture_kept`, :973-975). app/git_progress.py:683',
    'R-183': JOB_DEVICE.replace('{at}', 'app/git_progress.py:687'),
    'R-184': JOB_DEVICE.replace('{at}', 'app/git_progress.py:688'),
    'R-185': JOB_DEVICE.replace('. {at}', '. Choice: no folder involved. app/git_progress.py:692'),
    'R-186': JOB_DEVICE.replace('{at}', 'app/git_progress.py:696'),
    'R-187': JOB_DEVICE.replace('{at}', 'app/git_progress.py:698'),
    'R-188': JOB_DEVICE.replace('{at}', 'app/git_progress.py:702'),
    'R-189': JOB_DEVICE.replace('{at}', 'app/git_progress.py:704'),
    'R-190': JOB_DEVICE.replace('{at}', 'app/git_progress.py:708'),
    'R-191': JOB_DEVICE.replace('{at}', 'app/git_progress.py:716'),
    'R-192': JOB_DEVICE.replace('{at}', 'app/git_progress.py:718'),
    'R-193': JOB_DEVICE.replace('{at}', 'app/git_progress.py:720'),
    'R-194': JOB_DEVICE.replace('{at}', 'app/git_progress.py:735'),
    'R-195': JOB_DEVICE.replace('{at}', 'app/git_progress.py:743'),
    'R-196': JOB_DEVICE.replace('{at}', 'app/git_progress.py:762'),
    'R-197': JOB_DEVICE.replace('{at}', 'app/git_progress.py:766'),
    'R-198': JOB_DEVICE.replace('{at}', 'app/git_progress.py:768'),
    'R-199': JOB_DEVICE.replace('{at}', 'app/git_progress.py:770'),
    'R-200': JOB_DEVICE.replace('{at}', 'app/git_progress.py:772'),
    'R-201': VERSION409.replace('{at}', 'app/git_progress.py:792'),
    'R-202': VERSION409.replace('{at}', 'app/git_progress.py:794'),
    'R-203': VERSION409.replace('{at}', 'app/git_progress.py:799'),
    'R-204': VERSION409.replace('{at}', 'app/git_progress.py:800'),
    'R-205': VERSION409.replace('{at}', 'app/git_progress.py:802'),
    'R-206': VERSION409.replace('{at}', 'app/git_progress.py:805'),
    'R-207': VERSION409.replace('{at}', 'app/git_progress.py:807'),
    'R-208': VERSION409.replace('{at}', 'app/git_progress.py:811'),
    'R-209': VERSION409.replace('{at}', 'app/git_progress.py:816'),
    'R-210': 'Kept: message of an update a restart stopped (`dismissed`), in the job window. Choice: no folder involved. app/git_progress.py:921',
    'R-211': 'Kept: job `interrupted`; with a commit it waits for upload, without one the chip says Can\'t save → ' + CH['other'] + ' (DESIGN 7.1 row 6). Choice: no. app/git_progress.py:923',
    'R-212': 'Kept: ' + CH['settings'] + ' (`MANAGER_PROBLEMS`); HTTP 409 on the routes; a waiting save keeps the VM it was made on (3.1). app/git_progress.py:934',
    'R-213': 'Kept (carrier): every helper ValueError, scrubbed and cut to 600 characters, as `HelperProblem` (app/git_progress.py:938-940).',
    'R-214': 'Kept: ' + CH['vm'] + '. app/git_progress.py:55, 942',
    'R-215': 'Kept: ' + CH['vm'] + ' (prefix match in `MANAGER_PROBLEMS` :408); HTTP 409 when the chooser lists repositories. app/git_progress.py:947',
    'R-216': 'Kept: HTTP 409 on the list routes; chip `other`. app/git_progress.py:948',
    'R-217': 'Kept: HTTP 404 for a lab removed while the page was open; the place routes say `Lab not found.` too (app/git_place.py:41, 100, 375). app/git_progress.py:953',
    'R-218': 'Kept: HTTP 409 only for a request about a lab without a save location from a stale page: Save opens the first-save panel instead and Load reads through a repository of the VM (`reader` :885-902, DESIGN 3.7 Q3). Choice: no. app/git_progress.py:954, 967',
    'R-219': 'Kept (transient, 3.6 last paragraph): HTTP 409 while the design read-back of this lab runs. Choice: transient only. app/git_progress.py:980',
    'R-220': 'Kept (transient, 3.6 last paragraph): Save is disabled with the reason while work runs (DESIGN 7.1, `busy()` app.js); HTTP 409 otherwise. Choice: transient only. app/git_progress.py:983, 2211',
    'R-221': 'Kept (transient): HTTP 409 during a storage reset; the place route says the same (app/git_place.py:44, 321). Choice: transient only. app/git_progress.py:984',
    'R-222': 'Reworded: STILL_WAITING `A save is still waiting to be uploaded. Upload it, or open its Details and choose Keep snapshot only, then try again.` (app/git_progress.py:54, 986-988), now raised only by Remove lab and Start fresh (app/main.py:211, 247). Gone from link, destination, connect and unlink (DESIGN 3.1); a folder change while a save waits is question 3 (app/git_place.py:360-365). Choice: no.',
    'R-223': 'Gone (DESIGN 1, 3.4): no `guard_siblings`; another lab\'s waiting save no longer holds a save or an upload back, the review names it. Choice: no.',
    'R-224': 'Kept (transient): one placement at a time for the whole manager (`changing` app/git_progress.py:1080-1092) → HTTP 409 on …/git/place, …/git/state and the old routes while another lab\'s placement (a clone can take minutes) runs. Choice: yes, transient; covered by 3.6\'s last paragraph (9.6 M4). app/git_progress.py:1088',
    'R-225': 'Gone (DESIGN 1, 3.4, review F2): a move never uploads by itself; kept saves are named in the review (`also_sends_kept`, app/git_progress.py:2323-2361). Choice: no.',
    'R-226': 'Kept: HTTP 404 for a job id the manager no longer holds. app/git_progress.py:1155',
    'R-227': 'Kept for saves of older releases only (no own binding, DESIGN 3.1): job message → ' + CH['other'] + '. Choice: no. app/git_progress.py:1215',
    'R-228': 'Kept (carrier): the status problem of a move job, after `seen_status` gave the chip its code (app/git_progress.py:1234-1235).',
    'R-229': 'Gone (DESIGN 3.4, review F2): a move\'s commit waits for Upload like a save (`want_push` false app/git_place.py:415, app/git_progress.py:1858; `execute` :1228-1242). Choice: no.',
    'R-230': 'Gone (as R-229). Choice: no.',
    'R-231': 'Kept: message of a design export job (dismiss, generate again). Choice: no folder involved. app/git_progress.py:1249',
    'R-232': 'Kept: message of a design export job. Choice: no folder involved. app/git_progress.py:1256',
    'R-233': 'Kept (carrier): status problem of a design export (app/git_progress.py:1260-1260).',
    'R-234': 'Reworded: `No complete capture is available for retry. Start a new save.`; job `failed` → ' + CH['other'] + '. Choice: no. app/git_progress.py:1274',
    'R-235': 'Kept: job message → ' + CH['other'] + '. Choice: no. app/git_progress.py:1283',
    'R-236': 'Kept: job `interrupted` at shutdown. Choice: no. app/git_progress.py:1285',
    'R-237': 'Kept (internal guard): the capture reads exactly `job.node_names`, which the save route already cut to the devices in the lab (`selection` :1763-1768). Choice: no. app/git_progress.py:1297',
    'R-238': 'Kept: job message → ' + CH['other'] + '. Choice: no. app/git_progress.py:1303',
    'R-239': 'Kept (carrier): status problem of a save (app/git_progress.py:1307-1307).',
    'R-240': 'Kept: job message of an unexpected failure → ' + CH['other'] + '. app/git_progress.py:1337',
    'R-241': 'Kept: job message → ' + CH['other'] + '. app/git_progress.py:1370',
    'R-242': 'Kept on the old routes only (`folder_value`): HTTP 400; the place routes correct the characters (`clean_folder`, 2.5 step 1). FINDING F4 (G2, though a V row): a committed folder whose name holds a space or another character outside the pattern is choosable in the Progress tab and Use sends it to …/git/destination or …/folders. app/git_progress.py:862',
    'R-243': 'Kept (carrier of R-171) on the old routes: HTTP 400 (app/git_progress.py:863-864). FINDING F4 as R-171.',
    'R-244': 'Gone (DESIGN 4: the old routes lose the snapshot-conflict refusal): `snapshot_conflict` (app/git_progress.py:245-259) has no caller left; a folder at or below a saved state is the lab folder above it (2.5 step 2) or question 2. Choice: not on the manager; its browser copy still refuses in the Progress tab (git-places.js:139, 143; section E, 9.6 M5).',
    'R-245': 'Kept: HTTP 404 for a registration that left the VM (stale list); the place routes say `This repository is not on the VM. Refresh the list.` (app/git_place.py:37). app/git_progress.py:973, 1450',
    'R-246': 'Kept: HTTP 409 on the old …/git/connect (`bind_lab`); the place route raises the same text (app/git_place.py:40, 373). app/git_progress.py:1462',
    'R-247': 'Kept: HTTP 404 (`bind_lab`). app/git_progress.py:1464',
    'R-248': 'Kept: HTTP 400 on the old …/git/connect (`bind_lab`); the place route has the same text for an invalid explicit list only (app/git_place.py:34, 144). app/git_progress.py:1467',
    'R-249': 'Kept on the old POST …/git/connect (`bind_lab` app/git_progress.py:1468-1470); the place route asks question 1 instead (app/git_place.py:348-352). FINDING F2: Save settings › Connect by URL… (save-drawers.js:384, 395 → `gitConnectByUrl` git-progress.js:493-512) posts …/git/connect; a folder another lab is connected to (blank = the top level) ends here. app/git_progress.py:1470',
    'R-250': 'Kept: HTTP 500 (`bind_lab`); the place route has the same text (app/git_place.py:42, 394). app/git_progress.py:1480',
    'R-251': 'Kept: HTTP 404 (`rebind`, old destination route). app/git_progress.py:1509',
    'R-252': 'Kept: HTTP 500 (`rebind`). app/git_progress.py:1512',
    'R-253': 'Kept (carrier): `call()` turns a helper text into HTTP 409 on the old routes and the read routes (app/git_progress.py:1517-1519); the place routes use `invoke` with `clean_text` instead. Through it the collision sentence reaches a person on …/folders and …/connect (FINDING F2, F4).',
    'R-254': 'Kept (transient, DESIGN 3.1: a save that starts while its lab is placed waits): HTTP 409. Choice: transient only. app/git_progress.py:1565',
    'R-255': 'Kept (carrier): the helper\'s list error as HTTP 409 (app/git_progress.py:1684-1685; `catalog` :1424-1427 for the place routes).',
    'R-256': 'Kept: HTTP 404 (GET …/git). app/git_progress.py:1691',
    'R-257': 'Kept: HTTP 404 (PUT …/git). app/git_progress.py:1708',
    'R-258': 'Kept: HTTP 400 on PUT …/git for a registration that left the list (stale page). app/git_progress.py:1712',
    'R-259': 'Kept: HTTP 409 on PUT …/git. app/git_progress.py:1719',
    'R-260': 'Kept: HTTP 404 on PUT …/git. app/git_progress.py:1721',
    'R-261': 'Kept: HTTP 400 on PUT …/git (Save settings sends the ticked devices of this lab, save-drawers.js:439). app/git_progress.py:1724',
    'R-262': 'Reworded: `This folder is already connected to another lab (<lab>). Choose a different folder under Save settings.` (PUT …/git, app/git_progress.py:1725-1727). FINDING F3: Save settings › Use a different repository… (save-drawers.js:395 → `gitSwitchRepository` git-progress.js:485-491) offers every registration but the lab\'s own and hands it to the Progress tab form, which sends PUT …/git (git-progress.js:301); one another lab uses ends here. The place route would ask question 1.',
    'R-263': 'Kept: HTTP 500 (PUT …/git). app/git_progress.py:1733',
    'R-264': 'Kept: HTTP 400 on …/folders with `plan` (the Progress tab checks the name first); the chooser\'s New folder… uses …/folders/new, which never refuses a name (app/git_place.py:428-458). app/git_progress.py:1756',
    'R-265': 'Gone (DESIGN 2.7: a name that exists selects it): …/folders with `plan` answers `{selected}` or `{planned}` (app/git_progress.py:1757-1765); …/folders/new answers `existed: true` (app/git_place.py:449-458). Choice: no.',
    'R-266': 'Kept: HTTP 500; …/folders/new has the same text (app/git_place.py:43, 452). app/git_progress.py:1763',
    'R-267': 'Reworded: `The VM did not answer with the new folder. Try again.` (HTTP 409, …/folders). app/git_progress.py:1767',
    'R-268': 'Kept: HTTP 404 on DELETE …/folders (the chooser forgets planned folders only, save-drawers.js:614). app/git_progress.py:1779',
    'R-269': 'Kept: HTTP 500 (DELETE …/folders). app/git_progress.py:1783',
    'R-270': 'Kept: HTTP 409 on the old …/git/destination only. app/git_progress.py:1799',
    'R-271': 'Gone (DESIGN 3.3): the destination and place routes drop devices that left the lab from the new binding (app/git_progress.py:1803-1805, app/git_place.py:138-147); an empty selection is said by the next save (NO_DEVICES, 9.8). Choice: no.',
    'R-272': 'Gone: the own folder is no refusal (`destination` answers `saved` without a change, app/git_progress.py:1812-1813; the place route answers kind `own`, app/git_place.py:356-359). The words survive only as the move line\'s reason `This lab already saves in this folder.` (app/git_place.py:46, informational). Choice: no.',
    'R-273': 'Kept on the old POST …/git/destination (app/git_progress.py:1814-1817); the place route asks question 1. FINDING F4: reachable from the Progress tab\'s Use and New folder… (`gitApplyDestination` git-progress.js:439-441) when its tree is stale or the other lab connected meanwhile (the tab\'s own copy, section E, refuses first otherwise). app/git_progress.py:1817',
    'R-274': 'Reworded: `The repository connection changed meanwhile. Choose the folder again.` (race, old destination route). Choice: race only. app/git_progress.py:1831',
    'R-275': 'Reworded: `This lab\'s folder is no longer set up on the VM: … (Use a different repository… in Save settings).` (old destination route only). app/git_progress.py:1835-1837',
    'R-276': 'Kept (carrier): the helper\'s `register-prefix` text raw on the old destination route (app/git_progress.py:1841-1844), the collision sentence included (FINDING F4); `retired_already` follows a registration an older release retired.',
    'R-277': 'Reworded: `The VM did not answer with the new folder. Try again.` (HTTP 409). app/git_progress.py:1845',
    'R-278': 'Kept: HTTP 500 (old destination route). app/git_progress.py:1864',
    'R-279': 'Kept: HTTP 400 (old …/git/connect); the place route has the same text (app/git_place.py:33, 325, 331); the page always sends `acknowledge: true`. app/git_progress.py:1871',
    'R-280': 'Kept: HTTP 404 (old …/git/connect). app/git_progress.py:1876',
    'R-281': 'Reworded: `The VM did not answer with the repository. Try again.` (old …/git/connect); the place route says `The VM did not answer with the repository folder. Try again.` (app/git_place.py:38). app/git_progress.py:1883',
    'R-282': 'Kept: HTTP 404 (…/git/unlink). app/git_progress.py:1894',
    'R-283': 'Kept: HTTP 500 (…/git/unlink). app/git_progress.py:1899',
    'R-284': 'Kept: HTTP 400; the page sends a fixed target. app/git_progress.py:1931',
    'R-285': 'Kept: HTTP 400 for a typed checkpoint name; a checkpoint from a save derives its name (D6, :1790, 1814). app/git_progress.py:1935',
    'R-286': 'Kept: HTTP 400. app/git_progress.py:1936',
    'R-287': 'Kept: HTTP 400 from `note_value`, also for renames and lab-state names. app/git_progress.py:470',
    'R-288': 'Gone (D2, DESIGN 3.2): an empty name is allowed and the manager names the save (app/git_progress.py:1313-1320); a lab state still needs a name (`Give the lab state a name.` :2032, 9.8). The Progress tab\'s first-save dialog still refuses an empty name in the browser (`gitValidateLabel` git-progress.js:85, section E).',
    'R-289': 'Kept, not reachable through the page: each request gets a new id and a resend repeats its body (app/git_progress.py:1941-1944). Choice: no. app/git_progress.py:1943',
    'R-290': 'Reworded: `Reconnect the original VM before saving.` (HTTP 409; also for a lab state, :1898). app/git_progress.py:1964',
    'R-291': 'Reworded: NO_DEVICES `None of the devices this lab saves exist in it any more. Choose the devices under Save settings.` (app/git_progress.py:52, 1903-1911), only when no device of the selection is left; devices that left are dropped and the save goes on (3.3). A refusal of POST …/git/save shows ' + CH['other'] + ' (9.6 M1). Choice: no folder involved.',
    'R-292': 'Kept: HTTP 404. app/git_progress.py:1974',
    'R-293': 'Kept (carrier): `captured_snapshot` texts as HTTP 400 (app/git_progress.py:1977-1978).',
    'R-294': 'Kept: HTTP 400 when a stored capture holds other devices than the selection. app/git_progress.py:1979',
    'R-295': 'Kept: HTTP 500. app/git_progress.py:2015',
    'R-296': 'Kept: HTTP 400 (design export). app/git_progress.py:2108',
    'R-297': 'Kept: HTTP 400 (design export). app/git_progress.py:2109',
    'R-298': 'Kept: HTTP 503 (design export). app/git_progress.py:2110',
    'R-299': 'Kept, not reachable through the page: as R-289. Choice: no. app/git_progress.py:2115',
    'R-300': 'Kept: HTTP 409 (design export). app/git_progress.py:2120',
    'R-301': 'Kept: HTTP 404 (design export). app/git_progress.py:2122',
    'R-302': 'Kept: HTTP 409 (design export of a plan that did not succeed). Choice: no folder involved. app/git_progress.py:2123',
    'R-303': 'Kept (carrier): `design_snapshot` text as HTTP 400 (app/git_progress.py:2124-2125).',
    'R-304': 'Kept: HTTP 500 (design export). app/git_progress.py:2138',
    'R-305': 'Kept: HTTP 409 on POST …/git/jobs/{id}/retry for a save without a complete capture or one dismissed without a commit. Choice: no folder involved. app/git_progress.py:2178',
    'R-306': 'Kept for saves of older releases only (`job_binding` default text, app/git_progress.py:990-997); a save made since carries its binding. Choice: no. app/git_progress.py:990',
    'R-307': 'Kept: HTTP 409; `gitReviewJob` is the only sender of `{push: true, reviewed: true}` (DESIGN 7.3), so the page meets it only from a stale tab. Choice: no. app/git_progress.py:47, 2184, 2215',
    'R-308': 'Gone (DESIGN 3.4, review F2): no `kept_refusal`; a move is uploaded like any save after the review that names the kept saves. Choice: no.',
    'R-309': 'Gone (DESIGN 1, 3.4): no `sibling_refusal`; the upload sentence names the other saves. Choice: no.',
    'R-310': 'Kept: HTTP 400; the Keep snapshot only dialog sends `acknowledge: true`. app/git_progress.py:2224',
    'R-311': 'Kept: HTTP 500 (update). app/git_progress.py:2243',
    'R-312': 'Kept (carrier): `read-version` texts via `call()` and `decoded_snapshot` as HTTP 409 (app/git_progress.py:2283-2285).',
    'R-313': 'Kept: HTTP 404 for a save of another checkout opened from a lab. app/git_progress.py:2316',
    'R-314': 'Kept for saves of older releases only (`job_binding` with this text). app/git_progress.py:2312',
    'R-315': 'Kept: HTTP 400; restore.py has the same text (:625). app/git_progress.py:2362',
    'R-316': 'Kept (carrier): the helper\'s compare text via `call()` as HTTP 409 in the What changed drawer (app/git_progress.py:2332).',

    # ---------------------------------------------------------------- C. restore (Load)
    'R-317': 'Kept: per-device reason in the Load confirmation (`restoreReasonParts`, load.js:47, 223-225); the device is not loaded. app/restore.py:55, 715',
    'R-318': 'Kept: per-device reason; a state without restore data is View only in the Load list (`saved_device_reason`). app/restore.py:51',
    'R-319': 'Kept: per-device reason (preflight) and HTTP 409 at submit (`_probe`). app/restore.py:56',
    'R-320': 'Kept: per-device reason and job target message. app/restore.py:57',
    'R-321': 'Kept: informational diff note in the Load differences drawer. app/restore.py:222',
    'R-322': 'Kept: informational diff note. app/restore.py:225',
    'R-323': 'Kept: HTTP 404. app/restore.py:510',
    'R-324': 'Kept (transient): HTTP 409; the Load button is disabled while a load runs and the red Load says `A save is running.` during a save (DESIGN 7.1, load.js:307). Choice: transient only. app/restore.py:571',
    'R-325': 'Kept (transient): HTTP 409 during a storage reset. Choice: transient only. app/restore.py:573',
    'R-326': 'Kept (carrier): a `git` source\'s read errors as HTTP 409 in the Load review (app/restore.py:589-590).',
    'R-327': 'Kept: HTTP 404. app/restore.py:599',
    'R-328': 'Kept (carrier): `captured_snapshot` text as HTTP 400 for a backup source (app/restore.py:605-606).',
    'R-329': 'Kept: HTTP 400. app/restore.py:621',
    'R-330': 'Kept: HTTP 400. app/restore.py:625',
    'R-331': 'Kept (carrier): the status problem of the lab\'s own repository as HTTP 409 in the Load review (app/restore.py:636-638); another repository reads HEAD from `history` instead (:629-634).',
    'R-332': 'Kept (carrier): folder-source read errors as HTTP 409 (app/restore.py:643-644).',
    'R-333': 'Kept: HTTP 400. app/restore.py:653',
    'R-334': 'Kept: per-device reason, shown as `Not in this lab` (load.js:224). app/restore.py:52',
    'R-335': 'Kept: per-device reason (View only). app/restore.py:53',
    'R-336': 'Kept: per-device reason. app/restore.py:54',
    'R-337': 'Kept: per-device reason; the preflight is unchanged (DESIGN 3.7 Q2). Choice: not a folder; lab state outside the save flow. app/restore.py:717',
    'R-338': 'Kept: per-device reason (preflight unchanged). Choice: not a folder. app/restore.py:719',
    'R-339': 'Kept: HTTP 404. app/restore.py:741',
    'R-340': 'Kept: per-device reason (stale discovery). Choice: not a folder. app/restore.py:750',
    'R-341': 'Kept: informational, the device stays eligible. app/restore.py:769',
    'R-342': 'Kept: per-device reason. app/restore.py:774',
    'R-343': 'Kept: HTTP 404. app/restore.py:835',
    'R-344': 'Kept: HTTP 400; the confirmation\'s Load is disabled until a device is ticked (`Tick at least one device.`, load.js:307). app/restore.py:842',
    'R-345': 'Kept: HTTP 409 shown in the Load confirmation (load.js:287-288). app/restore.py:845',
    'R-346': 'Kept: HTTP 409 shown in the Load confirmation. Choice: not a folder. app/restore.py:861',
    'R-347': 'Kept: HTTP 409. Choice: not a folder. app/restore.py:864',
    'R-348': 'Kept: HTTP 500. app/restore.py:886',
    'R-349': 'Kept: load job fails before any device is touched; Load result view and job window. Choice: not a folder. app/restore.py:921',
    'R-350': 'Kept: as R-349. Choice: not a folder. app/restore.py:923',
    'R-351': 'Kept: as R-349. Choice: not a folder. app/restore.py:925',
    'R-352': 'Kept: as R-349. Choice: not a folder. app/restore.py:938',
    'R-353': 'Kept: as R-349. app/restore.py:949',
    'R-354': 'Kept: as R-349. app/restore.py:953',
    'R-355': 'Kept: target message `Configuration was not changed. Connectivity: <exception>` in the Load result (the script missed it: the text is a concatenation). app/restore.py:1132',
    'R-356': 'Kept: reason of an interrupted load\'s re-check (internal `LookupError`). app/restore.py:1305',
    'R-357': 'Kept: HTTP 404. app/restore.py:1452',
    'R-358': 'Kept: HTTP 400; `loadSubmit` is the only sender of `acknowledge: true` (DESIGN 5). app/restore.py:1497',
    'R-359': 'Kept: per-device reason after the `UNUSABLE` prefix. app/restore_eos.py:68, app/restore_junos.py:79, app/restore_iosxr.py:129',
    'R-360': 'Kept: per-device reason (both texts unchanged; the row joins two). app/restore_eos.py:71, app/restore_iosxr.py:132',
    'R-361': 'Kept: per-device reason. app/restore_eos.py:74, app/restore_iosxr.py:135, app/restore_junos.py:83',
    'R-362': 'Kept: per-device reason. app/restore_iosxr.py:137',
    'R-363': 'Kept: per-device reason, verbatim under Details. app/restore_iosxr.py:555',
    'R-364': 'Kept: per-device reason. app/restore_junos.py:81',
    'R-365': 'Kept: per-device reason, verbatim under Details. app/restore_junos.py:117, 143',

    # ---------------------------------------------------------------- D. deploy scripts
    'R-369': TERMINAL.replace('{at}', 'deploy/git-onboard.py:155-160'),
    'R-383': 'Reworded: `latest, baseline and checkpoints are the folders a save writes inside a lab folder. Choose the folder above them.`; terminal only, the wizard asks again (`ask_subfolder` loop). Choice in the manager: no. deploy/git-onboard.py:326-328',
    'R-386': 'Gone as a dead end (H1, DESIGN 2.4): a repository new to the manager is still registered at its top level (deploy/git-onboard.py:349-350), but that registration blocks no folder below it and, used by no lab, is invisible and reused or replaced.',
    'R-387': 'Gone (H1): no refusal; the wizard asks `This repository already holds at least one registered lab folder; choose a folder for the new lab, or leave it blank for the top level.` and accepts blank (deploy/git-onboard.py:369-370). Choice in the manager: no.',
    'R-408': TERMINAL.replace('{at}', 'deploy/setup-git.sh:12-15'),
    'R-422': 'Gone (H1) as the overlap rule: the embedded registration refuses only a real collision, with the helper\'s collision sentence (deploy/setup-git.sh:102-104 → `h.collision_message`); terminal only. Choice in the manager: no.',
    'R-423': 'Kept, moved into `GitRepository.register()` (app/host_git.py:1104), which the child calls (deploy/setup-git.sh:120); terminal output (setup-git.sh:136-138).',
    'R-424': 'Kept, moved into `register()` (app/host_git.py:1116); terminal output.',
    'R-425': 'Kept for the first folder of a checkout, moved into `check_synchronized` (app/host_git.py:53, 565); a further folder may sit on waiting manager saves (H2); terminal output.',
    'R-426': TERMINAL.replace('{at}', 'deploy/setup-git.sh:129'),
    'R-427': 'Kept (carrier): `print(str(error))`, exit 3 for an identity or login problem, else 1 (deploy/setup-git.sh:136-138).',
    'R-428': 'Kept: deploy/setup-git.sh:142, now with one hint for exit 1 (:144, new) and the guided-setup hints for exit 3 (:145-150); terminal only.',
}
# The rest of section D is printed by the deploy scripts on the VM terminal and is unchanged.
for n in list(range(366, 383)) + list(range(384, 386)) + list(range(388, 408)) + list(range(409, 422)):
    OUT.setdefault('R-%03d' % n, TERMINAL)

# ---------------------------------------------------------------- R2: rows whose outcome changed since R1 (2578f22)
OLD_ROUTE = ('Kept, not reachable through the page: only the old routes raise it (…/git/destination, …/folders, …/git/connect, '
             'PUT …/git), and no page script calls them any more (pinned by tests/test_save_router_ui.js:113-118); the page '
             'places a lab through POST …/git/place, which ')
OUT.update({
    'R-006': 'Kept: ' + PLACE409 + ' (the page checks `https://…` first, save-header.js:396, save-drawers.js:585). {at}',
    'R-031': 'Kept: only in `register()` (app/host_git.py:1117): ' + PLACE409 + '; 3.6 lists the account that cannot upload. {at}',
    'R-064': kc('busy', ' (M2 closed: app/git_progress.py:346, DESIGN 3.4)'),
    'R-067': kc('busy', ' (M2 closed: app/git_progress.py:345)'),
    'R-086': 'Kept, not reachable through the page: the options are booleans the manager sets; `checkpoint_only` (H8) only with a checkpoint from an existing capture (app/git_progress.py:1994). {at}',
    'R-125': 'Question (empty): `<name> is empty. The manager adds a README.md file to start it.` · **Start the repository** (H4; app/git_place.py:247-256, `initialize` app/host_git.py:1144); the page reaches `connect` only through POST …/git/place (F2 closed). app/host_git.py:56, 1144',
    'R-132': kc('other', ' (move job); the chooser offers the move only when the folder the lab leaves holds saved files (`bring` reason `nothing`, app/git_place.py:180); the old destination route applies the same rule (`brings_files` app/git_progress.py:553-558, 1818-1830)'),
    'R-136': kc('other', ' (move job)') + ' Choice: no; the chooser never offers the move into a folder that holds saved files (`bring` reason `not-empty`, app/git_place.py:180, 48) and the old destination route no longer queues it (`brings_files` app/git_progress.py:553-558, 1818-1830; F4 closed).',
    'R-145': 'Kept, not reachable through the page: the helper cuts a label it generates to 100 characters (`folder_label` app/host_git.py:1328-1341, used at :1375 and :1396); only a label an administrator types for `setup-git.sh --label` meets it (terminal). F1 closed. {at}',
    'R-146': 'Gone (H1): inside, above, beside and the top level are accepted (`colliding` app/host_git.py:157-167, `check_collision` :1353-1356); a real collision gets the collision sentence (9.8), which the place route turns into a replace or question 1 with one button (app/git_place.py:279-299). The old routes that passed it raw are no longer called by the page (F2, F4 closed). Choice: no.',
    'R-150': 'Kept, not reachable through the page: internal guard on the child\'s answer; on the place route it would read `The VM could not use this folder right now. Try again in a moment.` (`clean_text`, code `other`). {at}',
    'R-152': 'Reworded on the place route: `The VM could not use this folder right now. Try again in a moment.` (`clean_text` app/git_place.py:39, 58-61), recorded with code `busy`, so the chooser shows ' + CH['busy'] + ' (app/git_progress.py:427, save-drawers.js:609-619); transient (registry lock wait 30 s). Choice: transiently only. {at}',
    'R-154': 'Kept (race under the registry lock): a colliding folder saved meanwhile is replaced or asked about (app/git_place.py:284-299); the same folder saved meanwhile reads `The VM could not use this folder right now…` with code `busy` (chip sentence `Someone is working in this repository on the VM.`), and Try again reuses it. Choice: only by a race (transient). {at}',
    'R-171': OLD_ROUTE + 'uses the folder above a saved-state name instead (2.5 step 2). F4 closed. Choice: no. app/git_progress.py:235, 863-864',
    'R-183': 'Kept: save job ends `capture_incomplete` → ' + CH['device'] + ' (status.js:357-368); HTTP 400 for a checkpoint or baseline from such a capture. app/git_progress.py:627',
    'R-224': 'Kept (transient): one placement at a time for the whole manager; a second one now waits up to 10 s (`CONNECTION_WAIT`, app/git_progress.py:57, 1080-1090) and only then answers 409 (only while a clone of minutes runs). M4 closed. Choice: transiently only. app/git_progress.py:1088',
    'R-233': 'Kept (carrier): the status problem of a design export (`first_status` app/git_progress.py:1195-1202, raised at :1201).',
    'R-239': 'Kept (carrier): the status problem of a save (`first_status` app/git_progress.py:1195-1202, raised at :1201), after the VM copy was brought up to date when nothing waits (`catch_up` :1172-1193).',
    'R-242': OLD_ROUTE + 'corrects the characters (`clean_folder`, 2.5 step 1). F4 closed. app/git_progress.py:862',
    'R-243': OLD_ROUTE + 'never refuses a saved-state name. F4 closed. app/git_progress.py:863-864',
    'R-244': 'Gone (DESIGN 4: the old routes lose the snapshot-conflict refusal): `snapshot_conflict` has no caller; a folder at or below a saved state is the lab folder above it (2.5 step 2) or question 2. Its browser copy (`gitFolderChoice` git-places.js:126-148) is dead code: no page caller (section E). Choice: no.',
    'R-246': 'Kept: only on the old …/git/connect (not called by the page); the place route raises the same text (app/git_place.py:40, 373) when the VM connection changes during a placement. app/git_progress.py:1462',
    'R-247': OLD_ROUTE + 'says `Lab not found.` (app/git_place.py:41). app/git_progress.py:1464',
    'R-248': 'Kept: only on the old …/git/connect (not called by the page); the place route has the same text for an explicit device list that names a device the lab no longer has (app/git_place.py:34, 144; Save settings sends its ticks through it, save-drawers.js:449). app/git_progress.py:1467',
    'R-249': OLD_ROUTE + 'asks question 1 (app/git_place.py:348-352). F2 closed. Choice: no. app/git_progress.py:1470',
    'R-250': 'Kept: HTTP 500 on the old …/git/connect (not called by the page); the place route has the same text (app/git_place.py:42, 394). app/git_progress.py:1480',
    'R-251': OLD_ROUTE + 'never answers this (old destination only). app/git_progress.py:1509',
    'R-252': OLD_ROUTE + 'never answers this (old destination only). app/git_progress.py:1512',
    'R-253': 'Kept (carrier): `call()` turns a helper text into HelperRefused, an HTTP 409, on the read routes and the old routes (app/git_progress.py:1517-1519); the place and state routes record it as the lab\'s status first (`placement_refused`, `records_refusal` :2018-2024). The old routes are no longer called by the page (F2, F4 closed).',
    'R-255': 'Kept (carrier): the helper\'s list error as HTTP 409 (GET /api/git/repositories app/git_progress.py:1683-1685; `catalog` :1424-1427 as HelperRefused for the place routes).',
    'R-257': OLD_ROUTE + 'says `Lab not found.`. app/git_progress.py:1708',
    'R-258': OLD_ROUTE + 'says `This repository is not on the VM. Refresh the list.` (app/git_place.py:37). app/git_progress.py:1712',
    'R-259': 'Kept: only on the old PUT …/git (not called by the page); the place route has the same text (app/git_place.py:40, 373). app/git_progress.py:1719',
    'R-260': OLD_ROUTE + 'says `Lab not found.`. app/git_progress.py:1721',
    'R-261': 'Kept: only on the old PUT …/git (not called by the page); Save settings now sends the ticked devices through POST …/git/place (save-drawers.js:449), which has the same text (app/git_place.py:34, 144). app/git_progress.py:1724',
    'R-262': OLD_ROUTE + 'asks question 1; Use a different repository… opens the chooser on that repository (git-progress.js:132-139). F3 closed. Choice: no. app/git_progress.py:1727',
    'R-263': 'Kept: HTTP 500 on the old PUT …/git (not called by the page); the place route has the same text. app/git_progress.py:1733',
    'R-264': OLD_ROUTE + 'has New folder… through …/folders/new, which makes `folder` from an empty name (app/git_place.py:428-458). app/git_progress.py:1756',
    'R-266': 'Kept: HTTP 500 of …/folders/new when the planned folder could not be stored (app/git_place.py:43, 452); the old …/folders is not called by the page. app/git_progress.py:1763',
    'R-267': 'Reworded: `The VM did not answer with the new folder. Try again.`; old …/folders only, not called by the page (Kept, not reachable). app/git_progress.py:1767',
    'R-268': 'Kept: HTTP 404 on DELETE …/folders (the chooser\'s Remove from the list acts on planned folders only, save-drawers.js:687). app/git_progress.py:1779',
    'R-270': OLD_ROUTE + 'reads the lab\'s VM itself. app/git_progress.py:1799',
    'R-273': OLD_ROUTE + 'asks question 1. F4 closed. Choice: no. app/git_progress.py:1817',
    'R-274': 'Reworded: `The repository connection changed meanwhile. Choose the folder again.`; old destination only, not called by the page (Kept, not reachable). app/git_progress.py:1831',
    'R-275': 'Reworded: `This lab\'s folder is no longer set up on the VM: …`; old destination only, not called by the page (Kept, not reachable). app/git_progress.py:1835-1837',
    'R-276': 'Kept (carrier) on the old destination route only (app/git_progress.py:1841-1844), which the page no longer calls. F4 closed.',
    'R-277': 'Reworded: `The VM did not answer with the new folder. Try again.`; old destination only (Kept, not reachable). app/git_progress.py:1845',
    'R-278': OLD_ROUTE + 'reports a move it cannot queue as `move_reason` (app/git_place.py:51, 422). app/git_progress.py:1864',
    'R-279': 'Kept, not reachable through the page: the old …/git/connect is not called and the place route\'s copy (app/git_place.py:33, 325, 331) is never met because the page always sends `acknowledge: true`. app/git_progress.py:1871',
    'R-280': OLD_ROUTE + 'says `Lab not found.`. app/git_progress.py:1876',
    'R-281': 'Reworded: `The VM did not answer with the repository. Try again.` (old …/git/connect, not called by the page); the place route says `The VM did not answer with the repository folder. Try again.` (app/git_place.py:38). app/git_progress.py:1883',
    'R-288': 'Gone (D2, DESIGN 3.2): an empty name is allowed and the manager names the save (app/git_progress.py:1315-1322); no page script refuses it any more (`gitValidateLabel` is gone); a lab state still needs a name (`Give the lab state a name.` :2032, 9.8).',
    'R-291': 'Reworded: NO_DEVICES `None of the devices this lab saves exist in it any more. Choose the devices under Save settings.` (app/git_progress.py:52, 1903-1911), only when no device of the selection is left; it is recorded with code `devices`, so the chip says ' + CH['devices'] + ' (M1 closed). Choice: no folder involved.',
    'R-307': 'Kept: HTTP 409, also when an upload names no reviewed HEAD (app/git_progress.py:2187); `gitReviewJob` is the only sender of `{push: true, reviewed: true, head}` (DESIGN 7.3), so the page meets it only from a stale tab. Choice: no. app/git_progress.py:47, 2185, 2187',
    'R-317': 'Kept: per-device reason in the Load confirmation (`restoreReasonParts`, load.js:51, 231-233); the device is not loaded. app/restore.py:55, 715',
    'R-334': 'Kept: per-device reason, shown as `Not in this lab` (load.js:232). app/restore.py:52',
    'R-344': 'Kept: HTTP 400; the confirmation\'s Load is disabled until a device is ticked, with `Tick at least one device.` beside it (load.js:249). app/restore.py:842',
    'R-345': 'Kept: HTTP 409 shown in the Load confirmation (load.js:303-304). app/restore.py:845',
    'R-324': 'Kept (transient): HTTP 409; the Load button is disabled while a load runs and the red Load says `A save is running.` during a save (DESIGN 7.1, load.js:247). Choice: transient only. app/restore.py:571',
})

# ---------------------------------------------------------------- E. the page (R2, 2578f22). Paths are under app/static/.
DEAD = ('Kept, not reachable through the page: dead code. `{fn}` (git-places.js:{lines}) has no caller in the page scripts '
        '(only tests/test_git_places_ui.js); the chooser that replaced it prints the manager\'s answer (folderAnswerView git-places.js:358-428). ')
OUT.update({
    'R-429': 'Gone (D1, DESIGN 7.6): the lab banner no longer carries save problems; the chip says Can\'t save and its panel the code\'s sentence and actions (`saveProblem` status.js:350-379).',
    'R-430': DEAD.format(fn='gitFolderName', lines='9-13') + 'A typed name is corrected, never refused (`folderClean` :209-218).',
    'R-431': DEAD.format(fn='gitFolderPath', lines='20-27') + 'An empty Folder field means the top level; an empty New folder… name makes `folder` (app/git_place.py:442).',
    'R-432': DEAD.format(fn='gitFolderPath', lines='19-27') + 'Live: a saved-state name is the folder above it: `<typed> is part of a saved state, so <lab> saves in <folder>, the lab folder above it.` (:379). Choice: no.',
    'R-433': DEAD.format(fn='gitFolderChoice', lines='124-148') + 'Live: Save here is disabled only while the folders load or the VM is unreachable, with the reason beside it (:479-480, 510-513).',
    'R-434': DEAD.format(fn='gitFolderChoice', lines='124-148') + 'Live: step 2, the lab folder above, said in the sentence (:379). Choice: no.',
    'R-435': DEAD.format(fn='gitFolderChoice', lines='124-148') + 'Live: the lab folder above (2.5 step 2); a lab folder\'s latest, baseline and checkpoints are not listed in the tree (`folderChildren` :286-296). Choice: no.',
    'R-436': DEAD.format(fn='gitFolderChoice', lines='124-148') + 'Live: a checkpoint folder resolves to its lab folder (step 2). Choice: no.',
    'R-437': DEAD.format(fn='gitFolderChoice', lines='124-148') + 'Live: question 2 `This folder holds the state "<name>".` · Save beside it · Use this folder anyway (flat layout) (:404-410). Choice: no.',
    'R-438': DEAD.format(fn='gitFolderChoice', lines='124-148') + 'Live: a folder below a flat state is `free` (DESIGN 2.2: disjoint); below a `latest` it is the lab folder above. Choice: no.',
    'R-439': 'Gone (H1): no rule left; a folder inside another lab\'s folder is `free` (app/git_places.py `classify`). Choice: no.',
    'R-440': DEAD.format(fn='gitFolderChoice', lines='124-148') + 'Live: kind `own`: `<lab> already saves here.` · **Keep saving here** (:396), not a refusal. Choice: no.',
    'R-441': DEAD.format(fn='gitFolderChoice', lines='124-148') + 'Live: Question 1 `<lab> saves here too.` · Save in <folder>/<lab> · Use this folder anyway (:398-403). Choice: no.',
    'R-442': 'Gone (H1, DESIGN 2.4): a registration no lab uses is invisible; the answer is `free` and marks nothing. Choice: no.',
    'R-443': 'Gone (H1): the top level is `free` beside other lab folders (DESIGN 2.7). Choice: no.',
    'R-444': 'Gone (H1): subfolders are `free` below a lab at the top level. Choice: no.',
    'R-445': 'Gone (H1): a folder above other lab folders is `free`. Choice: no.',
    'R-446': 'Gone (DESIGN 2.7): New folder… is always enabled (git-places.js:494); inside a saved state the folder is made in the lab folder above and the chooser says so (save-drawers.js:672). The constant `GIT_NO_NEW_FOLDER` and `gitCanCreateIn` (:151-156) are dead code. Choice: no.',
    'R-447': 'Gone (D1): browse mode (the chooser\'s Browse the repository…) lists a folder\'s files with **Load this state…** and **View files** (`folderListingMarkup` git-places.js:350-356).',
    'R-448': 'Gone (as R-446). Choice: no.',
    'R-449': 'Reworded: `<folder> is new. It appears in the repository with the first save.` with the tag New (git-places.js:413, folderTreeMarkup); a planned folder is never worded as existing.',
    'R-450': 'Kept: `The folders could not be loaded. <manager sentence>` · Try again; an unreachable VM: `The lab VM cannot be reached, so its folders cannot be shown.` · Try again · Check the VM connection… (git-places.js:480-483).',
    'R-451': 'Gone (D1): no tick box; the panels say `Saved files can contain passwords or keys.` (save-header.js:17) and the page sends `acknowledge: true` with the place request.',
    'R-452': 'Gone (D2): no name is asked; an empty name is the manager\'s automatic one (app/git_progress.py:1315-1322).',
    'R-453': 'Gone (D2): the name field of a finished save has `maxlength="120"` (save-header.js:157); the manager checks the length too (`Use a name of at most 120 characters.` app/git_progress.py:430).',
    'R-454': 'Gone (D1): the header Save is disabled while a save of the lab runs and the chip says `Saving…` (save-header.js:295-300). Choice: transient only.',
    'R-455': 'Reworded: the header Save is disabled with `<what runs> Save is available when it finishes.` as visible text under it (#save-reason, save-header.js:298-300). Choice: transient only.',
    'R-456': 'Gone (D1): there is no Save menu; Save and Load are the two header buttons, each disabled only with its reason (save-header.js:295-301).',
    'R-457': 'Gone (D1, 7.6): the chip says Can\'t save and its panel the cause\'s sentence (9.2); the helper\'s own text is under Details and in Save settings › Git details › Status (save-drawers.js:413).',
    'R-458': 'Gone (D1): the drawers say `The saved versions could not be loaded.` / `The save settings could not be loaded.` with the manager\'s sentence and Try again (save-drawers.js:263, 421).',
    'R-459': 'Reworded: Save settings lists `No supported configuration devices in this lab.` (save-drawers.js:406); the first-save panel of a lab without devices says `This lab has no device whose configuration can be saved.` (save-header.js:177-181).',
    'R-460': 'Kept: Save settings › Save settings with no device ticked: `Choose at least one device to include.` (save-drawers.js:447).',
    'R-461': 'Gone (DESIGN 2.7): New folder… with a name that exists selects it: `<folder> already exists. It is selected.` (save-drawers.js:672; app/git_place.py:449-458). Choice: no.',
    'R-462': 'Kept: the address field of the first-save panel (SAVE_URL_ERROR save-header.js:18, 396) and of the chooser\'s Connect by URL… (save-drawers.js:585).',
    'R-463': 'Gone (D1): the first-save dialog is gone; a first save uses the lab\'s supported devices (app/git_place.py:138-151).',
    'R-464': 'Reworded: Choose a backup as starting point… disables its button and says why: `No complete backup includes all <n> devices yet. Save first, then choose Use as starting point… on that save.` (git-progress.js:201-203).',
    'R-465': 'Kept: Keep as a checkpoint\'s name field (All versions) (save-drawers.js:308).',
    'R-466': 'Reworded: `Choose a backup.` (git-progress.js:207).',
    'R-467': 'Reworded: `Tick the box to replace the current starting point.` (git-progress.js:208).',
    'R-468': 'Reworded: the upload sentence names every save the upload carries (`saveChangeSentence` status.js:383-410, `saveFailedSentence` save-header.js:74-80), informational.',
    'R-469': 'Gone (D1): Upload is in the chip panel; `push` opens it (git-progress.js:413).',
    'R-470': 'Kept: the Update from the repository dialog (git-progress.js:350-353); while saves wait the chip offers Upload instead (3.6).',
    'R-471': 'Reworded: `A save of this lab still waits for upload. It stays on the lab VM and stays part of the next upload.` (git-progress.js:355-358), informational; disconnecting is not refused (DESIGN 3.1, 7.6).',
    'R-472': 'Reworded: `View or download only: it was saved without the files needed to load it.` (git-progress.js:392); in the lists the row is View only with its reason.',
    'R-473': 'Gone (D1): `#git-problem` is no longer in index.html; the chip carries it.',
    'R-474': 'Kept: network-design.js:886 (design export with no generated plan). Choice: not a folder.',
    'R-475': 'Reworded: `Save this lab once first (Save in the lab’s header): the export goes into the folder the lab saves to.` (network-design.js:887). Choice: not a folder.',
    'R-476': 'Gone (D1): `restoreFromFolder` is gone; a folder is loaded from the chooser\'s Browse or the lists, with its path (the manager keeps `Choose a saved folder to apply.`, app/restore.py:621).',
    'R-477': 'Reworded: the Load panel: `<name> cannot be loaded right now.` with the manager\'s sentence · Try again · Back (load.js:281); a busy manager is a wait, `<name> can be loaded in a moment.` (load.js:278-279).',
    'R-478': 'Reworded: the confirmation lists the device with its word and reason and a disabled tick box (load.js:266); an action that helps is offered beside it (load.js:265).',
    'R-479': 'Reworded: `None of the devices can be loaded right now.` (load.js:257) with each device\'s reason.',
    'R-480': 'Reworded: the red Load is disabled with its reason beside it (`loadRunReason` load.js:244-251, #load-run-reason).',
    'R-481': 'Reworded: `Tick at least one device.` beside the disabled red Load (load.js:249).',
    'R-482': 'Gone (D4): the red Load is the acknowledgement (restore.js:163-166).',
    'R-483': 'Kept: restore job window while it reads the devices back (restore.js:336). Choice: transient only.',
    'R-484': 'Kept: `STATUS_RESTORE_RECHECK_DETAIL` (status.js:30), the chip says Checking devices…. Choice: transient only.',
    'R-485': 'Gone (D1, 7.1): `saveChipState` (status.js:306-348) says Can\'t save and `saveProblem` the cause.',
    'R-486': 'Reworded: chip Upload failed; panel `Your save is safe on the lab VM, but it could not be uploaded to <host>.` (save-header.js:76) · Try again.',
    'R-487': 'Reworded: chip Can\'t save with the cause\'s sentence (`saveProblem`, 9.2); job window `Configurations read — saving to the repository needs attention` (git-progress.js:9).',
    'R-488': 'Reworded: chip `device`: `<device> could not be read, so nothing was saved.` · Try again · Save settings · Details (status.js:364-368).',
    'R-489': 'Reworded: chip Can\'t save → `The save did not work.` · Try again · Details (status.js:379); job window `Save failed` (git-progress.js:9).',
    'R-490': 'Reworded: an interrupted save with a commit waits for upload; without one the chip says Can\'t save (DESIGN 7.1 rows 6, 8); job window `Save interrupted — retry it` (git-progress.js:9).',
})
