# Ansible inventory created from ['/home/clabllm/research/netlab-integration/proto-external/run-default/topology.yml', 'package:topology-defaults.yml']
#

all:
  hosts: {}
as65000:
  hosts:
    ceos: {}
    cjunosevolved: {}
    vjunos-switch: {}
    xrv9k: {}
custom_configs:
  hosts: {}
daemons:
  hosts: {}
eos:
  hosts:
    ceos:
      ansible_host: 172.20.20.101
      id: 1
iosxr:
  hosts:
    xrv9k:
      ansible_host: 172.20.20.104
      id: 4
linux:
  hosts:
    host1:
      ansible_host: 172.20.20.105
      id: 5
modules:
  hosts:
    ceos: {}
    cjunosevolved: {}
    host1: {}
    vjunos-switch: {}
    xrv9k: {}
netlab_no_collect:
  hosts:
    host1: {}
netlab_no_reload:
  hosts:
    host1: {}
netlab_normalize:
  hosts:
    ceos: {}
netlab_ready_ansible:
  hosts:
    cjunosevolved: {}
    vjunos-switch: {}
unprovisioned:
  hosts: {}
vjunos_switch:
  hosts:
    vjunos-switch:
      ansible_host: 172.20.20.103
      id: 3
vptx:
  hosts:
    cjunosevolved:
      ansible_host: 172.20.20.102
      id: 2
