// Builds the lab builder's editor bundle into ../app/static/lab-builder (committed; never built on a lab VM).
//   node build.mjs          rebuild the committed assets
//   node build.mjs --check  rebuild into a scratch folder and compare with the committed manifest
import { build } from "esbuild";
import { createHash } from "node:crypto";
import { mkdirSync, mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync, existsSync, copyFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";

const CHECK = process.argv.includes("--check");
const TARGET = resolve("../app/static/lab-builder");
const OUT = CHECK ? mkdtempSync(join(tmpdir(), "lab-builder-")) : TARGET;
const ASSETS = join(OUT, "assets");
if (!CHECK) rmSync(TARGET, { recursive: true, force: true });
mkdirSync(ASSETS, { recursive: true });

const stubs = { name: "builder-stubs", setup(b) {
  b.onResolve({ filter: /^monaco-editor$/ }, () => ({ path: resolve("src/monaco-stub.ts") }));
  b.onResolve({ filter: /MonacoCodeEditor-[A-Z0-9]+\.js$/ }, () => ({ path: resolve("src/monaco-stub.ts") }));
} };
const result = await build({
  entryPoints: { main: "src/main.tsx" }, outdir: ASSETS, bundle: true, format: "esm", splitting: true, minify: true, sourcemap: false,
  target: "es2022", jsx: "automatic", chunkNames: "c-[hash]", assetNames: "[name]-[hash]", legalComments: "none", logLevel: "warning",
  define: { "process.env.NODE_ENV": '"production"' }, loader: { ".ttf": "file", ".woff": "file", ".woff2": "file", ".svg": "file", ".png": "file" },
  publicPath: "/static/lab-builder/assets", plugins: [stubs], metafile: true
});

// font-src falls back to 'self': a font embedded in a stylesheet as data: is refused. Move any to a file.
for (const f of readdirSync(ASSETS).filter((n) => n.endsWith(".css"))) {
  const p = join(ASSETS, f);
  writeFileSync(p, readFileSync(p, "utf8").replace(/url\((["']?)data:font\/(ttf|woff2?);base64,([A-Za-z0-9+/=]+)\1\)/g, (_m, _q, ext, b64) => {
    const buf = Buffer.from(b64, "base64"), name = "font-" + createHash("sha256").update(buf).digest("hex").slice(0, 10) + "." + ext;
    writeFileSync(join(ASSETS, name), buf); return `url(/static/lab-builder/assets/${name})`;
  }));
}

// Third-party notices: every package that contributed to the bundle, with its licence text.
const packages = new Map();
for (const input of Object.keys(result.metafile.inputs)) {
  const hits = [...input.matchAll(/node_modules\/((?:@[^/]+\/)?[^/]+)/g)]; if (!hits.length) continue;
  const last = hits[hits.length - 1], dir = input.slice(0, last.index + last[0].length);
  if (packages.has(dir)) continue;
  const pkg = JSON.parse(readFileSync(join(dir, "package.json"), "utf8"));
  const file = readdirSync(dir).find((n) => /^licen[sc]e/i.test(n));
  packages.set(dir, { name: pkg.name, version: pkg.version, license: typeof pkg.license === "string" ? pkg.license : JSON.stringify(pkg.license ?? "see package"), text: file ? readFileSync(join(dir, file), "utf8").trim() : "" });
}
const rows = [...packages.values()].sort((a, b) => a.name.localeCompare(b.name));
const notices = ["Third-party software in the lab builder's editor bundle (app/static/lab-builder/assets).",
  "Generated by clab-backup-ui/lab-builder/build.mjs from the packages esbuild bundled. No package is modified.",
  "elkjs is distributed under the Eclipse Public License 2.0; its source is available at https://github.com/kieler/elkjs.", "",
  ...rows.map((r) => `${r.name} ${r.version} (${r.license})`), "",
  ...rows.flatMap((r) => ["=".repeat(78), `${r.name} ${r.version} (${r.license})`, "=".repeat(78), r.text || "(the package ships no licence file; see its licence identifier above)", ""])].join("\n");
writeFileSync(join(OUT, "THIRD-PARTY-NOTICES.txt"), notices);
copyFileSync("node_modules/@containerlab/clab-ui/LICENSE", join(OUT, "clab-ui.LICENSE"));

const manifest = {}; let total = 0;
for (const f of readdirSync(ASSETS).sort()) { const d = readFileSync(join(ASSETS, f)); manifest[f] = createHash("sha256").update(d).digest("hex"); total += d.length; }
const text = JSON.stringify({ editor: "@containerlab/clab-ui 0.3.2", files: manifest }, null, 1) + "\n";
if (CHECK) {
  const committed = existsSync(join(TARGET, "manifest.json")) ? readFileSync(join(TARGET, "manifest.json"), "utf8") : "";
  rmSync(OUT, { recursive: true, force: true });
  if (committed !== text) { console.error("The committed lab builder assets do not match a fresh build. Run: node build.mjs"); process.exit(1); }
  console.log("Committed lab builder assets match a fresh build:", Object.keys(manifest).length, "files");
} else {
  writeFileSync(join(OUT, "manifest.json"), text);
  console.log("lab builder assets:", Object.keys(manifest).length, "files,", total, "bytes,", rows.length, "packages");
}
