#!/usr/bin/env python3
"""Drive the *Network design* tab in a real browser against the fixture manager (real app, real engine, no VM).

Starts `docs/redesign/tools/fixture_manager.py` on a fresh data directory (the pinned `netlab` must be on
PATH: run with the application venv's bin first), opens the seeded `ospf-basics` lab (two cEOS, one XRv9k,
no `mgmt` block), and walks the student's path: an empty design, a refused pool, a saved design, a plan
generated by the real engine, its files and download, an unsupported protocol refused before the engine
runs, a reload that keeps the design, the export link, and a narrow viewport. Console and page errors
are collected for the whole run. Writes screenshots and a Markdown report.

    PATH="$PWD/clab-backup-ui/.venv/bin:$PATH" clab-backup-ui/.venv/bin/python \\
        docs/netlab-integration/tools/check_design_ui.py [--port 8095] [--shots DIR] [--report FILE] [--keep]

Exit status 1 when a check failed or an unexpected console/page error was seen.
"""
import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile
import time
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

from playwright.sync_api import sync_playwright

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
FIXTURE = ROOT / 'docs' / 'redesign' / 'tools' / 'fixture_manager.py'
HANDLED = 'Failed to load resource: the server responded with a status of '
LAB = 'ospf-basics'


class Run:
    def __init__(self, page, shots):
        self.page, self.shots_dir = page, shots
        self.console, self.pageerrors, self.checks, self.shots = [], [], [], []
        page.on('console', lambda m: self.console.append({'type': m.type, 'text': m.text}) if m.type == 'error' else None)
        page.on('pageerror', lambda e: self.pageerrors.append(str(e)))

    def check(self, name, ok, detail=''):
        self.checks.append({'name': name, 'ok': bool(ok), 'detail': str(detail)[:300]})
        print(('  ok   ' if ok else '  FAIL ') + name + ('' if ok else ': ' + str(detail)[:200]), flush=True)

    def shot(self, name):
        path = self.shots_dir / (name + '.png')
        self.page.screenshot(path=str(path), full_page=True)
        self.shots.append(path)

    def text(self, selector):
        node = self.page.locator(selector).first
        return (node.text_content() or '') if node.count() else ''

    def wait_state(self, words, timeout=90000):
        self.page.wait_for_function('(w) => (document.getElementById("design-state")?.textContent || "").includes(w)', arg=words, timeout=timeout)


def wait_http(url, seconds=60):
    deadline = time.monotonic() + seconds
    while time.monotonic() < deadline:
        try:
            with urllib.request.urlopen(url, timeout=2) as response:
                if response.status == 200: return json.loads(response.read())
        except Exception:
            time.sleep(0.5)
    raise SystemExit('fixture manager did not answer at ' + url)


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--port', type=int, default=8095)
    parser.add_argument('--shots', default=str(HERE.parent / 'evidence' / 'shots'))
    parser.add_argument('--report', default=str(HERE.parent / 'evidence' / 'browser-design-ui.md'))
    parser.add_argument('--keep', action='store_true', help='keep the fixture data directory')
    args = parser.parse_args()
    if not shutil.which('netlab'): raise SystemExit('netlab is not on PATH: run with the application venv first')
    shots = Path(args.shots); shots.mkdir(parents=True, exist_ok=True)
    data = Path(tempfile.mkdtemp(prefix='design-ui-fixture-'))
    base = 'http://127.0.0.1:%d' % args.port
    fixture = subprocess.Popen([sys.executable, str(FIXTURE), '--port', str(args.port), '--data', str(data)],
                               stdout=subprocess.DEVNULL, stderr=subprocess.STDOUT)
    started = datetime.now(timezone.utc).isoformat(timespec='seconds')
    try:
        state = wait_http(base + '/api/state')
        lab = next(l for l in state['labs'] if l['name'] == LAB)
        with sync_playwright() as pw:
            browser = pw.chromium.launch()
            chromium_version = browser.version
            page = browser.new_page(viewport={'width': 1440, 'height': 900})
            r = Run(page, shots)
            page.goto(base + '/#lab=' + lab['id'] + '&view=design')
            page.wait_for_selector('#design-view:not([hidden])', timeout=15000)
            page.wait_for_function('() => !(document.getElementById("design-state")?.textContent || "").includes("Loading")', timeout=15000)
            r.check('Design tab opens from the route', page.locator('#tab-design[aria-selected="true"]').count() == 1)
            r.check('a lab without a design says so', 'No design yet' in r.text('#design-state'), r.text('#design-state'))
            r.check('the devices table lists the three devices with their profiles',
                    all(name in r.text('#design-devices') for name in ('r1', 'r2', 'r3')) and 'eos' in r.text('#design-devices') and 'iosxr' in r.text('#design-devices'), r.text('#design-devices'))
            r.shot('01-empty')
            # A pool inside the (default) management network is refused with the path named.
            page.fill('#design-pool-lan-ipv4', '172.20.20.0/24')
            page.locator('#design-pool-lan-ipv4').dispatch_event('change')
            page.click('#design-save')
            page.wait_for_function('() => (document.getElementById("design-problems")?.textContent || "").length > 0', timeout=10000)
            r.check('a pool inside the management network is refused', 'management' in r.text('#design-problems') and 'addressing.lan.ipv4' in r.text('#design-problems'), r.text('#design-problems'))
            r.shot('02-problems')
            page.fill('#design-pool-lan-ipv4', '172.16.0.0/16')
            page.locator('#design-pool-lan-ipv4').dispatch_event('change')
            # OSPF and BGP through the guided controls, then save.
            for module in ('ospf', 'bgp'):
                box = page.locator('input[name="design-module"][value="%s"]' % module)
                if not box.is_checked(): box.check()
            page.fill('#design-bgp-as', '65010')
            page.locator('#design-bgp-as').dispatch_event('change')
            r.check('editing marks the design as unsaved', 'Unsaved' in r.text('#design-state'), r.text('#design-state'))
            page.click('#design-save')
            page.wait_for_function('() => !(document.getElementById("design-state")?.textContent || "").includes("Unsaved")', timeout=10000)
            r.check('the design saves without problems', r.text('#design-problems').strip() == '' and 'problems' not in r.text('#design-state').lower(), r.text('#design-state') + ' | ' + r.text('#design-problems'))
            page.locator('#design-view h2').first.click()   # leave the form: the editor catches up when no input has focus
            page.wait_for_timeout(300)
            advanced = page.locator('#design-advanced').input_value()
            r.check('the advanced editor shows the saved intent with the guided values', '"bgp"' in advanced and '65010' in advanced and '"ospf"' in advanced, advanced[:200])
            r.shot('03-saved')
            # The guided tables of 1.30.46: a VRF, a static route and a link's VRF through the form, mirrored into the JSON.
            for table in ('design-vrfs', 'design-vlans', 'design-links', 'design-static'):
                r.check('the %s table is rendered' % table, page.locator('#' + table).count() == 1)
            page.click('#design-vrf-add')
            page.wait_for_selector('[data-design-vrf-key]', timeout=5000)
            name_box = page.locator('[data-design-vrf-key] [data-design-vrf-field="name"]').first
            name_box.fill('red'); name_box.dispatch_event('change')
            page.locator('#design-view h2').first.click()   # the row is keyed by its name once the field is left
            page.wait_for_selector('[data-design-vrf-key="red"]', timeout=5000)
            loop_box = page.locator('[data-design-vrf-key="red"] [data-design-vrf-field="loopback"]').first
            if not loop_box.is_checked(): loop_box.check()
            link_vrf = page.locator('[data-design-link-key] [data-design-link-field="vrf"]').first
            link_vrf.select_option('red'); link_vrf.dispatch_event('change')
            page.click('#design-static-add')
            page.wait_for_selector('[data-design-static-key]', timeout=5000)
            prefix_box = page.locator('[data-design-static-key] [data-design-static-field="prefix"]').first
            prefix_box.fill('192.0.2.0/24'); prefix_box.dispatch_event('change')
            page.locator('#design-view h2').first.click()
            page.wait_for_timeout(400)
            advanced = page.locator('#design-advanced').input_value()
            r.check('a VRF added through the table reaches the JSON with its loopback', '"red"' in advanced and '"loopback": true' in advanced, advanced[:300])
            r.check('the link table attaches the link to the VRF', '"vrf": "red"' in advanced, advanced[:300])
            r.check('a static route added through the table reaches the JSON', '"static"' in advanced and '192.0.2.0/24' in advanced and '"discard": true' in advanced, advanced[:300])
            r.check('the vrf and routing modules were switched on with the tables', '"vrf"' in advanced and '"routing"' in advanced, advanced[:300])
            page.click('#design-save')
            page.wait_for_function('() => !(document.getElementById("design-state")?.textContent || "").includes("Unsaved")', timeout=10000)
            r.check('the design with the guided tables saves without problems', r.text('#design-problems').strip() == '', r.text('#design-problems'))
            r.shot('03b-tables')
            # Generate with the real engine.
            page.click('#design-generate')
            r.wait_state('Generating', timeout=10000)
            r.wait_state('Plan ready', timeout=120000)
            plan = r.text('#design-plan')
            r.check('the plan lists every device with a loopback and interfaces', all(n in plan for n in ('r1', 'r2', 'r3')) and 'Ethernet1' in plan and 'GigabitEthernet0/0/0/0' in plan, plan[:400])
            r.check('the plan shows the containerlab ports beside the device ports', 'eth1' in plan and 'Gi0/0/0/0' in plan, plan[:400])
            r.check('BGP sessions appear in the plan', '65010' in plan, plan[:400])
            compat = r.text('#design-compatibility')
            r.check('compatibility says generated, not live tested', 'not yet tested live' in compat.lower() or 'not live' in compat.lower(), compat[:300])
            files = r.text('#design-files')
            r.check('the files card lists initial, ospf, bgp, vrf and routing for a device', all(m in files for m in ('initial', 'ospf', 'bgp', 'vrf', 'routing')), files[:300])
            r.check('the ZIP download link points at the generation', '/design/generations/' in (page.locator('#design-download').get_attribute('href') or ''), page.locator('#design-download').get_attribute('href'))
            r.shot('04-plan')
            page.locator('#design-files button', has_text='View').first.click()
            page.wait_for_selector('dialog[open] pre', timeout=10000)
            r.check('a generated file opens in a dialog', len(page.locator('dialog[open] pre').first.inner_text()) > 20)
            r.shot('05-file')
            page.keyboard.press('Escape')
            # An unsupported protocol is refused before the engine runs.
            page.locator('input[name="design-module"][value="eigrp"]').check()
            page.click('#design-save')
            page.wait_for_function('() => !(document.getElementById("design-state")?.textContent || "").includes("Unsaved")', timeout=10000)
            page.click('#design-generate')
            r.wait_state('failed', timeout=60000)
            errors = r.text('#design-plan-errors')
            r.check('EIGRP on cEOS fails the plan with the device and the reason named', 'eigrp' in errors and ('r1' in errors or 'r2' in errors) and 'arista_ceos' in errors, errors[:300])
            r.shot('06-unsupported')
            page.locator('input[name="design-module"][value="eigrp"]').uncheck()
            page.click('#design-save')
            page.wait_for_function('() => !(document.getElementById("design-state")?.textContent || "").includes("Unsaved")', timeout=10000)
            # Reload keeps the design; the export link is there; the history lists both plans.
            page.reload()
            page.wait_for_selector('#design-view:not([hidden])', timeout=15000)
            page.wait_for_function('() => (document.getElementById("design-advanced")?.value || "").includes("65010")', timeout=15000)
            r.check('a reload keeps the saved design', '65010' in page.locator('#design-advanced').input_value())
            r.check('the history lists the generated plans', r.text('#design-history').count('Plan') >= 1 or 'generated' in r.text('#design-history').lower(), r.text('#design-history')[:300])
            r.check('the export item is present', page.locator('#design-export').count() == 1)
            page.set_viewport_size({'width': 768, 'height': 1024})
            page.wait_for_timeout(300)
            width = page.evaluate('() => document.documentElement.scrollWidth')
            r.check('no horizontal scroll at tablet width', width <= 768 + 1, 'scrollWidth=%s' % width)
            r.shot('07-tablet')
            # The shell itself is wider than a phone (the lab switcher and the Manager menu; a pre-existing layout
            # fact of every tab), so at phone width the Design tab must only add nothing to what the shell already has.
            page.set_viewport_size({'width': 390, 'height': 844})
            page.wait_for_timeout(300)
            design_width = page.evaluate('() => document.documentElement.scrollWidth')
            page.click('#tab-topology'); page.wait_for_timeout(300)
            shell_width = page.evaluate('() => document.documentElement.scrollWidth')
            page.click('#tab-design'); page.wait_for_timeout(300)
            r.check('the Design tab adds no horizontal overflow at phone width beyond the shell', design_width <= shell_width, 'design=%s shell=%s' % (design_width, shell_width))
            r.shot('08-phone')
            browser.close()
        handled = [e for e in r.console if e['text'].startswith(HANDLED)]
        real = [e for e in r.console if e not in handled]
        failed = [c for c in r.checks if not c['ok']]
        lines = ['# Browser check: Network design tab', '', 'Run ' + started + ' against the fixture manager (real app on scratch data `' + str(data) + '`, real `netlab` engine, no VM), Chromium ' + chromium_version + '.', '',
                 '%d of %d checks passed; %d console errors (%d handled HTTP responses); %d page errors.' % (len(r.checks) - len(failed), len(r.checks), len(real), len(handled), len(r.pageerrors)), '', '| Check | Result | Detail |', '|---|---|---|']
        for c in r.checks: lines.append('| ' + c['name'] + ' | ' + ('ok' if c['ok'] else 'FAIL') + ' | ' + c['detail'].replace('|', '\\|').replace('\n', ' ')[:160] + ' |')
        if real: lines += ['', 'Console errors:', ''] + ['- ' + e['text'][:300] for e in real]
        if r.pageerrors: lines += ['', 'Page errors:', ''] + ['- ' + e[:300] for e in r.pageerrors]
        lines += ['', 'Screenshots: ' + ', '.join(p.name for p in r.shots), '']
        Path(args.report).parent.mkdir(parents=True, exist_ok=True)
        Path(args.report).write_text('\n'.join(lines))
        print('\n'.join(lines[4:5]))
        return 1 if failed or real or r.pageerrors else 0
    finally:
        fixture.terminate()
        try: fixture.wait(timeout=10)
        except subprocess.TimeoutExpired: fixture.kill()
        if not args.keep: shutil.rmtree(data, ignore_errors=True)


if __name__ == '__main__':
    sys.exit(main())
